#
# Unicode Mapping generated by uni2python.xsl
#
unicode_map = {
0x00100: r"\={A}", # LATIN CAPITAL LETTER A WITH MACRON
0x00101: r"\={a}", # LATIN SMALL LETTER A WITH MACRON
0x00102: r"\u{A}", # LATIN CAPITAL LETTER A WITH BREVE
0x00103: r"\u{a}", # LATIN SMALL LETTER A WITH BREVE
0x00104: r"\k{A}", # LATIN CAPITAL LETTER A WITH OGONEK
0x00105: r"\k{a}", # LATIN SMALL LETTER A WITH OGONEK
0x00106: r"\'{C}", # LATIN CAPITAL LETTER C WITH ACUTE
0x00107: r"\'{c}", # LATIN SMALL LETTER C WITH ACUTE
0x00108: r"\^{C}", # LATIN CAPITAL LETTER C WITH CIRCUMFLEX
0x00109: r"\^{c}", # LATIN SMALL LETTER C WITH CIRCUMFLEX
0x0010A: r"\.{C}", # LATIN CAPITAL LETTER C WITH DOT ABOVE
0x0010B: r"\.{c}", # LATIN SMALL LETTER C WITH DOT ABOVE
0x0010C: r"\v{C}", # LATIN CAPITAL LETTER C WITH CARON
0x0010D: r"\v{c}", # LATIN SMALL LETTER C WITH CARON
0x0010E: r"\v{D}", # LATIN CAPITAL LETTER D WITH CARON
0x0010F: r"\v{d}", # LATIN SMALL LETTER D WITH CARON
0x00110: r"\DJ{}", # LATIN CAPITAL LETTER D WITH STROKE
0x00111: r"\dj{}", # LATIN SMALL LETTER D WITH STROKE
0x00112: r"\={E}", # LATIN CAPITAL LETTER E WITH MACRON
0x00113: r"\={e}", # LATIN SMALL LETTER E WITH MACRON
0x00114: r"\u{E}", # LATIN CAPITAL LETTER E WITH BREVE
0x00115: r"\u{e}", # LATIN SMALL LETTER E WITH BREVE
0x00116: r"\.{E}", # LATIN CAPITAL LETTER E WITH DOT ABOVE
0x00117: r"\.{e}", # LATIN SMALL LETTER E WITH DOT ABOVE
0x00118: r"\k{E}", # LATIN CAPITAL LETTER E WITH OGONEK
0x00119: r"\k{e}", # LATIN SMALL LETTER E WITH OGONEK
0x0011A: r"\v{E}", # LATIN CAPITAL LETTER E WITH CARON
0x0011B: r"\v{e}", # LATIN SMALL LETTER E WITH CARON
0x0011C: r"\^{G}", # LATIN CAPITAL LETTER G WITH CIRCUMFLEX
0x0011D: r"\^{g}", # LATIN SMALL LETTER G WITH CIRCUMFLEX
0x0011E: r"\u{G}", # LATIN CAPITAL LETTER G WITH BREVE
0x0011F: r"\u{g}", # LATIN SMALL LETTER G WITH BREVE
0x00120: r"\.{G}", # LATIN CAPITAL LETTER G WITH DOT ABOVE
0x00121: r"\.{g}", # LATIN SMALL LETTER G WITH DOT ABOVE
0x00122: r"\c{G}", # LATIN CAPITAL LETTER G WITH CEDILLA
0x00123: r"\c{g}", # LATIN SMALL LETTER G WITH CEDILLA
0x00124: r"\^{H}", # LATIN CAPITAL LETTER H WITH CIRCUMFLEX
0x00125: r"\^{h}", # LATIN SMALL LETTER H WITH CIRCUMFLEX
0x00126: r"{\fontencoding{LELA}\selectfont\char40}", # LATIN CAPITAL LETTER H WITH STROKE
0x00128: r"\~{I}", # LATIN CAPITAL LETTER I WITH TILDE
0x00129: r"\~{\i}", # LATIN SMALL LETTER I WITH TILDE
0x0012A: r"\={I}", # LATIN CAPITAL LETTER I WITH MACRON
0x0012B: r"\={\i}", # LATIN SMALL LETTER I WITH MACRON
0x0012C: r"\u{I}", # LATIN CAPITAL LETTER I WITH BREVE
0x0012D: r"\u{\i}", # LATIN SMALL LETTER I WITH BREVE
0x0012E: r"\k{I}", # LATIN CAPITAL LETTER I WITH OGONEK
0x0012F: r"\k{i}", # LATIN SMALL LETTER I WITH OGONEK
0x00130: r"\.{I}", # LATIN CAPITAL LETTER I WITH DOT ABOVE
0x00131: r"\i{}", # LATIN SMALL LETTER DOTLESS I
0x00132: r"IJ", # LATIN CAPITAL LIGATURE IJ
0x00133: r"ij", # LATIN SMALL LIGATURE IJ
0x00134: r"\^{J}", # LATIN CAPITAL LETTER J WITH CIRCUMFLEX
0x00135: r"\^{\j}", # LATIN SMALL LETTER J WITH CIRCUMFLEX
0x00136: r"\c{K}", # LATIN CAPITAL LETTER K WITH CEDILLA
0x00137: r"\c{k}", # LATIN SMALL LETTER K WITH CEDILLA
0x00138: r"{\fontencoding{LELA}\selectfont\char91}", # LATIN SMALL LETTER KRA
0x00139: r"\'{L}", # LATIN CAPITAL LETTER L WITH ACUTE
0x0013A: r"\'{l}", # LATIN SMALL LETTER L WITH ACUTE
0x0013B: r"\c{L}", # LATIN CAPITAL LETTER L WITH CEDILLA
0x0013C: r"\c{l}", # LATIN SMALL LETTER L WITH CEDILLA
0x0013D: r"\v{L}", # LATIN CAPITAL LETTER L WITH CARON
0x0013E: r"\v{l}", # LATIN SMALL LETTER L WITH CARON
0x0013F: r"{\fontencoding{LELA}\selectfont\char201}", # LATIN CAPITAL LETTER L WITH MIDDLE DOT
0x00140: r"{\fontencoding{LELA}\selectfont\char202}", # LATIN SMALL LETTER L WITH MIDDLE DOT
0x00141: r"\L{}", # LATIN CAPITAL LETTER L WITH STROKE
0x00142: r"\l{}", # LATIN SMALL LETTER L WITH STROKE
0x00143: r"\'{N}", # LATIN CAPITAL LETTER N WITH ACUTE
0x00144: r"\'{n}", # LATIN SMALL LETTER N WITH ACUTE
0x00145: r"\c{N}", # LATIN CAPITAL LETTER N WITH CEDILLA
0x00146: r"\c{n}", # LATIN SMALL LETTER N WITH CEDILLA
0x00147: r"\v{N}", # LATIN CAPITAL LETTER N WITH CARON
0x00148: r"\v{n}", # LATIN SMALL LETTER N WITH CARON
0x00149: r"'n", # LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
0x0014A: r"\NG{}", # LATIN CAPITAL LETTER ENG
0x0014B: r"\ng{}", # LATIN SMALL LETTER ENG
0x0014C: r"\={O}", # LATIN CAPITAL LETTER O WITH MACRON
0x0014D: r"\={o}", # LATIN SMALL LETTER O WITH MACRON
0x0014E: r"\u{O}", # LATIN CAPITAL LETTER O WITH BREVE
0x0014F: r"\u{o}", # LATIN SMALL LETTER O WITH BREVE
0x00150: r"\H{O}", # LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
0x00151: r"\H{o}", # LATIN SMALL LETTER O WITH DOUBLE ACUTE
0x00152: r"\OE{}", # LATIN CAPITAL LIGATURE OE
0x00153: r"\oe{}", # LATIN SMALL LIGATURE OE
0x00154: r"\'{R}", # LATIN CAPITAL LETTER R WITH ACUTE
0x00155: r"\'{r}", # LATIN SMALL LETTER R WITH ACUTE
0x00156: r"\c{R}", # LATIN CAPITAL LETTER R WITH CEDILLA
0x00157: r"\c{r}", # LATIN SMALL LETTER R WITH CEDILLA
0x00158: r"\v{R}", # LATIN CAPITAL LETTER R WITH CARON
0x00159: r"\v{r}", # LATIN SMALL LETTER R WITH CARON
0x0015A: r"\'{S}", # LATIN CAPITAL LETTER S WITH ACUTE
0x0015B: r"\'{s}", # LATIN SMALL LETTER S WITH ACUTE
0x0015C: r"\^{S}", # LATIN CAPITAL LETTER S WITH CIRCUMFLEX
0x0015D: r"\^{s}", # LATIN SMALL LETTER S WITH CIRCUMFLEX
0x0015E: r"\c{S}", # LATIN CAPITAL LETTER S WITH CEDILLA
0x0015F: r"\c{s}", # LATIN SMALL LETTER S WITH CEDILLA
0x00160: r"\v{S}", # LATIN CAPITAL LETTER S WITH CARON
0x00161: r"\v{s}", # LATIN SMALL LETTER S WITH CARON
0x00162: r"\c{T}", # LATIN CAPITAL LETTER T WITH CEDILLA
0x00163: r"\c{t}", # LATIN SMALL LETTER T WITH CEDILLA
0x00164: r"\v{T}", # LATIN CAPITAL LETTER T WITH CARON
0x00165: r"\v{t}", # LATIN SMALL LETTER T WITH CARON
0x00166: r"{\fontencoding{LELA}\selectfont\char47}", # LATIN CAPITAL LETTER T WITH STROKE
0x00167: r"{\fontencoding{LELA}\selectfont\char63}", # LATIN SMALL LETTER T WITH STROKE
0x00168: r"\~{U}", # LATIN CAPITAL LETTER U WITH TILDE
0x00169: r"\~{u}", # LATIN SMALL LETTER U WITH TILDE
0x0016A: r"\={U}", # LATIN CAPITAL LETTER U WITH MACRON
0x0016B: r"\={u}", # LATIN SMALL LETTER U WITH MACRON
0x0016C: r"\u{U}", # LATIN CAPITAL LETTER U WITH BREVE
0x0016D: r"\u{u}", # LATIN SMALL LETTER U WITH BREVE
0x0016E: r"\r{U}", # LATIN CAPITAL LETTER U WITH RING ABOVE
0x0016F: r"\r{u}", # LATIN SMALL LETTER U WITH RING ABOVE
0x00170: r"\H{U}", # LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
0x00171: r"\H{u}", # LATIN SMALL LETTER U WITH DOUBLE ACUTE
0x00172: r"\k{U}", # LATIN CAPITAL LETTER U WITH OGONEK
0x00173: r"\k{u}", # LATIN SMALL LETTER U WITH OGONEK
0x00174: r"\^{W}", # LATIN CAPITAL LETTER W WITH CIRCUMFLEX
0x00175: r"\^{w}", # LATIN SMALL LETTER W WITH CIRCUMFLEX
0x00176: r"\^{Y}", # LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
0x00177: r"\^{y}", # LATIN SMALL LETTER Y WITH CIRCUMFLEX
0x00178: r'\"{Y}', # LATIN CAPITAL LETTER Y WITH DIAERESIS
0x00179: r"\'{Z}", # LATIN CAPITAL LETTER Z WITH ACUTE
0x0017A: r"\'{z}", # LATIN SMALL LETTER Z WITH ACUTE
0x0017B: r"\.{Z}", # LATIN CAPITAL LETTER Z WITH DOT ABOVE
0x0017C: r"\.{z}", # LATIN SMALL LETTER Z WITH DOT ABOVE
0x0017D: r"\v{Z}", # LATIN CAPITAL LETTER Z WITH CARON
0x0017E: r"\v{z}", # LATIN SMALL LETTER Z WITH CARON
0x00195: r"\texthvlig{}", # LATIN SMALL LETTER HV
0x0019E: r"\textnrleg{}", # LATIN SMALL LETTER N WITH LONG RIGHT LEG
0x001C2: r"\textdoublepipe{}", # LATIN LETTER ALVEOLAR CLICK
0x001F5: r"\'{g}", # LATIN SMALL LETTER G WITH ACUTE
0x00261: r"g", # LATIN SMALL LETTER SCRIPT G
0x00278: r"\textphi{}", # LATIN SMALL LETTER PHI
0x0029E: r"\textturnk{}", # LATIN SMALL LETTER TURNED K
0x002A4: r"\textdyoghlig{}", # LATIN SMALL LETTER DEZH DIGRAPH
0x002BC: r"'", # MODIFIER LETTER APOSTROPHE
0x002C7: r"\textasciicaron{}", # CARON
0x002D8: r"\textasciibreve{}", # BREVE
0x002D9: r"\textperiodcentered{}", # DOT ABOVE
0x002DA: r"\r{}", # RING ABOVE
0x002DB: r"\k{}", # OGONEK
0x002DC: r"\texttildelow{}", # SMALL TILDE
0x002DD: r"\H{}", # DOUBLE ACUTE ACCENT
0x002E5: r"\tone{55}", # MODIFIER LETTER EXTRA-HIGH TONE BAR
0x002E6: r"\tone{44}", # MODIFIER LETTER HIGH TONE BAR
0x002E7: r"\tone{33}", # MODIFIER LETTER MID TONE BAR
0x002E8: r"\tone{22}", # MODIFIER LETTER LOW TONE BAR
0x002E9: r"\tone{11}", # MODIFIER LETTER EXTRA-LOW TONE BAR
0x00300: r"\`", # COMBINING GRAVE ACCENT
0x00301: r"\'", # COMBINING ACUTE ACCENT
0x00302: r"\^", # COMBINING CIRCUMFLEX ACCENT
0x00303: r"\~", # COMBINING TILDE
0x00304: r"\=", # COMBINING MACRON
0x00306: r"\u", # COMBINING BREVE
0x00307: r"\.", # COMBINING DOT ABOVE
0x00308: r'\"', # COMBINING DIAERESIS
0x0030A: r"\r", # COMBINING RING ABOVE
0x0030B: r"\H", # COMBINING DOUBLE ACUTE ACCENT
0x0030C: r"\v", # COMBINING CARON
0x0030F: r"\cyrchar\C", # COMBINING DOUBLE GRAVE ACCENT
0x00327: r"\c", # COMBINING CEDILLA
0x00386: r"\'{A}", # GREEK CAPITAL LETTER ALPHA WITH TONOS
0x00388: r"\'{E}", # GREEK CAPITAL LETTER EPSILON WITH TONOS
0x00389: r"\'{H}", # GREEK CAPITAL LETTER ETA WITH TONOS
0x0038A: r"\'{}{I}", # GREEK CAPITAL LETTER IOTA WITH TONOS
0x0038C: r"\'{}O", # GREEK CAPITAL LETTER OMICRON WITH TONOS
0x00393: r"$\Gamma$", # GREEK CAPITAL LETTER GAMMA
0x00394: r"$\Delta$", # GREEK CAPITAL LETTER DELTA
0x00395: r"$\Epsilon$", # GREEK CAPITAL LETTER EPSILON
0x003A0: r"$\Pi$", # GREEK CAPITAL LETTER PI
0x003A3: r"$\Sigma$", # GREEK CAPITAL LETTER SIGMA
0x003A4: r"$\Tau$", # GREEK CAPITAL LETTER TAU
0x003A5: r"$\Upsilon$", # GREEK CAPITAL LETTER UPSILON
0x003A6: r"$\Phi$", # GREEK CAPITAL LETTER PHI
0x003AC: r"\'{$\alpha$}", # GREEK SMALL LETTER ALPHA WITH TONOS
0x003AD: r"$\acute{\epsilon}$", # GREEK SMALL LETTER EPSILON WITH TONOS
0x003AE: r"$\acute{\eta}$", # GREEK SMALL LETTER ETA WITH TONOS
0x003AF: r"$\acute{\iota}$", # GREEK SMALL LETTER IOTA WITH TONOS
0x003B0: r"$\acute{\ddot{\upsilon}}$", # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
0x003B1: r"$\alpha$", # GREEK SMALL LETTER ALPHA
0x003B2: r"$\beta$", # GREEK SMALL LETTER BETA
0x003B3: r"$\gamma$", # GREEK SMALL LETTER GAMMA
0x003B4: r"$\delta$", # GREEK SMALL LETTER DELTA
0x003B5: r"$\epsilon$", # GREEK SMALL LETTER EPSILON
0x003B6: r"$\zeta$", # GREEK SMALL LETTER ZETA
0x003B7: r"$\eta$", # GREEK SMALL LETTER ETA
0x003B8: r"\texttheta{}", # GREEK SMALL LETTER THETA
0x003B9: r"$\iota$", # GREEK SMALL LETTER IOTA
0x003BA: r"$\kappa$", # GREEK SMALL LETTER KAPPA
0x003BB: r"$\lambda$", # GREEK SMALL LETTER LAMDA
0x003BC: r"$\mu$", # GREEK SMALL LETTER MU
0x003BD: r"$\nu$", # GREEK SMALL LETTER NU
0x003BE: r"$\xi$", # GREEK SMALL LETTER XI
0x003BF: r"$o$", # GREEK SMALL LETTER OMICRON
0x003C0: r"$\pi$", # GREEK SMALL LETTER PI
0x003C1: r"$\rho$", # GREEK SMALL LETTER RHO
0x003C3: r"$\sigma$", # GREEK SMALL LETTER SIGMA
0x003C4: r"$\tau$", # GREEK SMALL LETTER TAU
0x003C5: r"$\upsilon$", # GREEK SMALL LETTER UPSILON
0x003C6: r"$\varphi$", # GREEK SMALL LETTER PHI
0x003C7: r"$\chi$", # GREEK SMALL LETTER CHI
0x003C8: r"$\psi$", # GREEK SMALL LETTER PSI
0x003C9: r"$\omega$", # GREEK SMALL LETTER OMEGA
0x003CA: r"$\ddot{\iota}$", # GREEK SMALL LETTER IOTA WITH DIALYTIKA
0x003CB: r"$\ddot{\upsilon}$", # GREEK SMALL LETTER UPSILON WITH DIALYTIKA
0x003CC: r"\'{o}", # GREEK SMALL LETTER OMICRON WITH TONOS
0x003D1: r"\textvartheta{}", # GREEK THETA SYMBOL
0x003D5: r"$\phi$", # GREEK PHI SYMBOL
0x00401: r"\cyrchar\CYRYO{}", # CYRILLIC CAPITAL LETTER IO
0x00402: r"\cyrchar\CYRDJE{}", # CYRILLIC CAPITAL LETTER DJE
0x00403: r"\cyrchar{\'\CYRG}", # CYRILLIC CAPITAL LETTER GJE
0x00404: r"\cyrchar\CYRIE{}", # CYRILLIC CAPITAL LETTER UKRAINIAN IE
0x00405: r"\cyrchar\CYRDZE{}", # CYRILLIC CAPITAL LETTER DZE
0x00406: r"\cyrchar\CYRII{}", # CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I
0x00407: r"\cyrchar\CYRYI{}", # CYRILLIC CAPITAL LETTER YI
0x00408: r"\cyrchar\CYRJE{}", # CYRILLIC CAPITAL LETTER JE
0x00409: r"\cyrchar\CYRLJE{}", # CYRILLIC CAPITAL LETTER LJE
0x0040A: r"\cyrchar\CYRNJE{}", # CYRILLIC CAPITAL LETTER NJE
0x0040B: r"\cyrchar\CYRTSHE{}", # CYRILLIC CAPITAL LETTER TSHE
0x0040C: r"\cyrchar{\'\CYRK}", # CYRILLIC CAPITAL LETTER KJE
0x0040E: r"\cyrchar\CYRUSHRT{}", # CYRILLIC CAPITAL LETTER SHORT U
0x0040F: r"\cyrchar\CYRDZHE{}", # CYRILLIC CAPITAL LETTER DZHE
0x00410: r"\cyrchar\CYRA{}", # CYRILLIC CAPITAL LETTER A
0x00411: r"\cyrchar\CYRB{}", # CYRILLIC CAPITAL LETTER BE
0x00412: r"\cyrchar\CYRV{}", # CYRILLIC CAPITAL LETTER VE
0x00413: r"\cyrchar\CYRG{}", # CYRILLIC CAPITAL LETTER GHE
0x00414: r"\cyrchar\CYRD{}", # CYRILLIC CAPITAL LETTER DE
0x00415: r"\cyrchar\CYRE{}", # CYRILLIC CAPITAL LETTER IE
0x00416: r"\cyrchar\CYRZH{}", # CYRILLIC CAPITAL LETTER ZHE
0x00417: r"\cyrchar\CYRZ{}", # CYRILLIC CAPITAL LETTER ZE
0x00418: r"\cyrchar\CYRI{}", # CYRILLIC CAPITAL LETTER I
0x00419: r"\cyrchar\CYRISHRT{}", # CYRILLIC CAPITAL LETTER SHORT I
0x0041A: r"\cyrchar\CYRK{}", # CYRILLIC CAPITAL LETTER KA
0x0041B: r"\cyrchar\CYRL{}", # CYRILLIC CAPITAL LETTER EL
0x0041C: r"\cyrchar\CYRM{}", # CYRILLIC CAPITAL LETTER EM
0x0041D: r"\cyrchar\CYRN{}", # CYRILLIC CAPITAL LETTER EN
0x0041E: r"\cyrchar\CYRO{}", # CYRILLIC CAPITAL LETTER O
0x0041F: r"\cyrchar\CYRP{}", # CYRILLIC CAPITAL LETTER PE
0x00420: r"\cyrchar\CYRR{}", # CYRILLIC CAPITAL LETTER ER
0x00421: r"\cyrchar\CYRS{}", # CYRILLIC CAPITAL LETTER ES
0x00422: r"\cyrchar\CYRT{}", # CYRILLIC CAPITAL LETTER TE
0x00423: r"\cyrchar\CYRU{}", # CYRILLIC CAPITAL LETTER U
0x00424: r"\cyrchar\CYRF{}", # CYRILLIC CAPITAL LETTER EF
0x00425: r"\cyrchar\CYRH{}", # CYRILLIC CAPITAL LETTER HA
0x00426: r"\cyrchar\CYRC{}", # CYRILLIC CAPITAL LETTER TSE
0x00427: r"\cyrchar\CYRCH{}", # CYRILLIC CAPITAL LETTER CHE
0x00428: r"\cyrchar\CYRSH{}", # CYRILLIC CAPITAL LETTER SHA
0x00429: r"\cyrchar\CYRSHCH{}", # CYRILLIC CAPITAL LETTER SHCHA
0x0042A: r"\cyrchar\CYRHRDSN{}", # CYRILLIC CAPITAL LETTER HARD SIGN
0x0042B: r"\cyrchar\CYRERY{}", # CYRILLIC CAPITAL LETTER YERU
0x0042C: r"\cyrchar\CYRSFTSN{}", # CYRILLIC CAPITAL LETTER SOFT SIGN
0x0042D: r"\cyrchar\CYREREV{}", # CYRILLIC CAPITAL LETTER E
0x0042E: r"\cyrchar\CYRYU{}", # CYRILLIC CAPITAL LETTER YU
0x0042F: r"\cyrchar\CYRYA{}", # CYRILLIC CAPITAL LETTER YA
0x00430: r"\cyrchar\cyra{}", # CYRILLIC SMALL LETTER A
0x00431: r"\cyrchar\cyrb{}", # CYRILLIC SMALL LETTER BE
0x00432: r"\cyrchar\cyrv{}", # CYRILLIC SMALL LETTER VE
0x00433: r"\cyrchar\cyrg{}", # CYRILLIC SMALL LETTER GHE
0x00434: r"\cyrchar\cyrd{}", # CYRILLIC SMALL LETTER DE
0x00435: r"\cyrchar\cyre{}", # CYRILLIC SMALL LETTER IE
0x00436: r"\cyrchar\cyrzh{}", # CYRILLIC SMALL LETTER ZHE
0x00437: r"\cyrchar\cyrz{}", # CYRILLIC SMALL LETTER ZE
0x00438: r"\cyrchar\cyri{}", # CYRILLIC SMALL LETTER I
0x00439: r"\cyrchar\cyrishrt{}", # CYRILLIC SMALL LETTER SHORT I
0x0043A: r"\cyrchar\cyrk{}", # CYRILLIC SMALL LETTER KA
0x0043B: r"\cyrchar\cyrl{}", # CYRILLIC SMALL LETTER EL
0x0043C: r"\cyrchar\cyrm{}", # CYRILLIC SMALL LETTER EM
0x0043D: r"\cyrchar\cyrn{}", # CYRILLIC SMALL LETTER EN
0x0043E: r"\cyrchar\cyro{}", # CYRILLIC SMALL LETTER O
0x0043F: r"\cyrchar\cyrp{}", # CYRILLIC SMALL LETTER PE
0x00440: r"\cyrchar\cyrr{}", # CYRILLIC SMALL LETTER ER
0x00441: r"\cyrchar\cyrs{}", # CYRILLIC SMALL LETTER ES
0x00442: r"\cyrchar\cyrt{}", # CYRILLIC SMALL LETTER TE
0x00443: r"\cyrchar\cyru{}", # CYRILLIC SMALL LETTER U
0x00444: r"\cyrchar\cyrf{}", # CYRILLIC SMALL LETTER EF
0x00445: r"\cyrchar\cyrh{}", # CYRILLIC SMALL LETTER HA
0x00446: r"\cyrchar\cyrc{}", # CYRILLIC SMALL LETTER TSE
0x00447: r"\cyrchar\cyrch{}", # CYRILLIC SMALL LETTER CHE
0x00448: r"\cyrchar\cyrsh{}", # CYRILLIC SMALL LETTER SHA
0x00449: r"\cyrchar\cyrshch{}", # CYRILLIC SMALL LETTER SHCHA
0x0044A: r"\cyrchar\cyrhrdsn{}", # CYRILLIC SMALL LETTER HARD SIGN
0x0044B: r"\cyrchar\cyrery{}", # CYRILLIC SMALL LETTER YERU
0x0044C: r"\cyrchar\cyrsftsn{}", # CYRILLIC SMALL LETTER SOFT SIGN
0x0044D: r"\cyrchar\cyrerev{}", # CYRILLIC SMALL LETTER E
0x0044E: r"\cyrchar\cyryu{}", # CYRILLIC SMALL LETTER YU
0x0044F: r"\cyrchar\cyrya{}", # CYRILLIC SMALL LETTER YA
0x00451: r"\cyrchar\cyryo{}", # CYRILLIC SMALL LETTER IO
0x00452: r"\cyrchar\cyrdje{}", # CYRILLIC SMALL LETTER DJE
0x00453: r"\cyrchar{\'\cyrg}", # CYRILLIC SMALL LETTER GJE
0x00454: r"\cyrchar\cyrie{}", # CYRILLIC SMALL LETTER UKRAINIAN IE
0x00455: r"\cyrchar\cyrdze{}", # CYRILLIC SMALL LETTER DZE
0x00456: r"\cyrchar\cyrii{}", # CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
0x00457: r"\cyrchar\cyryi{}", # CYRILLIC SMALL LETTER YI
0x00458: r"\cyrchar\cyrje{}", # CYRILLIC SMALL LETTER JE
0x00459: r"\cyrchar\cyrlje{}", # CYRILLIC SMALL LETTER LJE
0x0045A: r"\cyrchar\cyrnje{}", # CYRILLIC SMALL LETTER NJE
0x0045B: r"\cyrchar\cyrtshe{}", # CYRILLIC SMALL LETTER TSHE
0x0045C: r"\cyrchar{\'\cyrk}", # CYRILLIC SMALL LETTER KJE
0x0045E: r"\cyrchar\cyrushrt{}", # CYRILLIC SMALL LETTER SHORT U
0x0045F: r"\cyrchar\cyrdzhe{}", # CYRILLIC SMALL LETTER DZHE
0x00460: r"\cyrchar\CYROMEGA{}", # CYRILLIC CAPITAL LETTER OMEGA
0x00461: r"\cyrchar\cyromega{}", # CYRILLIC SMALL LETTER OMEGA
0x00462: r"\cyrchar\CYRYAT{}", # CYRILLIC CAPITAL LETTER YAT
0x00464: r"\cyrchar\CYRIOTE{}", # CYRILLIC CAPITAL LETTER IOTIFIED E
0x00465: r"\cyrchar\cyriote{}", # CYRILLIC SMALL LETTER IOTIFIED E
0x00466: r"\cyrchar\CYRLYUS{}", # CYRILLIC CAPITAL LETTER LITTLE YUS
0x00467: r"\cyrchar\cyrlyus{}", # CYRILLIC SMALL LETTER LITTLE YUS
0x00468: r"\cyrchar\CYRIOTLYUS{}", # CYRILLIC CAPITAL LETTER IOTIFIED LITTLE YUS
0x00469: r"\cyrchar\cyriotlyus{}", # CYRILLIC SMALL LETTER IOTIFIED LITTLE YUS
0x0046A: r"\cyrchar\CYRBYUS{}", # CYRILLIC CAPITAL LETTER BIG YUS
0x0046C: r"\cyrchar\CYRIOTBYUS{}", # CYRILLIC CAPITAL LETTER IOTIFIED BIG YUS
0x0046D: r"\cyrchar\cyriotbyus{}", # CYRILLIC SMALL LETTER IOTIFIED BIG YUS
0x0046E: r"\cyrchar\CYRKSI{}", # CYRILLIC CAPITAL LETTER KSI
0x0046F: r"\cyrchar\cyrksi{}", # CYRILLIC SMALL LETTER KSI
0x00470: r"\cyrchar\CYRPSI{}", # CYRILLIC CAPITAL LETTER PSI
0x00471: r"\cyrchar\cyrpsi{}", # CYRILLIC SMALL LETTER PSI
0x00472: r"\cyrchar\CYRFITA{}", # CYRILLIC CAPITAL LETTER FITA
0x00474: r"\cyrchar\CYRIZH{}", # CYRILLIC CAPITAL LETTER IZHITSA
0x00478: r"\cyrchar\CYRUK{}", # CYRILLIC CAPITAL LETTER UK
0x00479: r"\cyrchar\cyruk{}", # CYRILLIC SMALL LETTER UK
0x0047A: r"\cyrchar\CYROMEGARND{}", # CYRILLIC CAPITAL LETTER ROUND OMEGA
0x0047B: r"\cyrchar\cyromegarnd{}", # CYRILLIC SMALL LETTER ROUND OMEGA
0x0047C: r"\cyrchar\CYROMEGATITLO{}", # CYRILLIC CAPITAL LETTER OMEGA WITH TITLO
0x0047D: r"\cyrchar\cyromegatitlo{}", # CYRILLIC SMALL LETTER OMEGA WITH TITLO
0x0047E: r"\cyrchar\CYROT{}", # CYRILLIC CAPITAL LETTER OT
0x0047F: r"\cyrchar\cyrot{}", # CYRILLIC SMALL LETTER OT
0x00480: r"\cyrchar\CYRKOPPA{}", # CYRILLIC CAPITAL LETTER KOPPA
0x00481: r"\cyrchar\cyrkoppa{}", # CYRILLIC SMALL LETTER KOPPA
0x00482: r"\cyrchar\cyrthousands{}", # CYRILLIC THOUSANDS SIGN
0x00488: r"\cyrchar\cyrhundredthousands{}", # COMBINING CYRILLIC HUNDRED THOUSANDS SIGN
0x00489: r"\cyrchar\cyrmillions{}", # COMBINING CYRILLIC MILLIONS SIGN
0x0048C: r"\cyrchar\CYRSEMISFTSN{}", # CYRILLIC CAPITAL LETTER SEMISOFT SIGN
0x0048D: r"\cyrchar\cyrsemisftsn{}", # CYRILLIC SMALL LETTER SEMISOFT SIGN
0x0048E: r"\cyrchar\CYRRTICK{}", # CYRILLIC CAPITAL LETTER ER WITH TICK
0x0048F: r"\cyrchar\cyrrtick{}", # CYRILLIC SMALL LETTER ER WITH TICK
0x00490: r"\cyrchar\CYRGUP{}", # CYRILLIC CAPITAL LETTER GHE WITH UPTURN
0x00491: r"\cyrchar\cyrgup{}", # CYRILLIC SMALL LETTER GHE WITH UPTURN
0x00492: r"\cyrchar\CYRGHCRS{}", # CYRILLIC CAPITAL LETTER GHE WITH STROKE
0x00493: r"\cyrchar\cyrghcrs{}", # CYRILLIC SMALL LETTER GHE WITH STROKE
0x00494: r"\cyrchar\CYRGHK{}", # CYRILLIC CAPITAL LETTER GHE WITH MIDDLE HOOK
0x00495: r"\cyrchar\cyrghk{}", # CYRILLIC SMALL LETTER GHE WITH MIDDLE HOOK
0x00496: r"\cyrchar\CYRZHDSC{}", # CYRILLIC CAPITAL LETTER ZHE WITH DESCENDER
0x00497: r"\cyrchar\cyrzhdsc{}", # CYRILLIC SMALL LETTER ZHE WITH DESCENDER
0x00498: r"\cyrchar\CYRZDSC{}", # CYRILLIC CAPITAL LETTER ZE WITH DESCENDER
0x00499: r"\cyrchar\cyrzdsc{}", # CYRILLIC SMALL LETTER ZE WITH DESCENDER
0x0049A: r"\cyrchar\CYRKDSC{}", # CYRILLIC CAPITAL LETTER KA WITH DESCENDER
0x0049B: r"\cyrchar\cyrkdsc{}", # CYRILLIC SMALL LETTER KA WITH DESCENDER
0x0049C: r"\cyrchar\CYRKVCRS{}", # CYRILLIC CAPITAL LETTER KA WITH VERTICAL STROKE
0x0049D: r"\cyrchar\cyrkvcrs{}", # CYRILLIC SMALL LETTER KA WITH VERTICAL STROKE
0x0049E: r"\cyrchar\CYRKHCRS{}", # CYRILLIC CAPITAL LETTER KA WITH STROKE
0x0049F: r"\cyrchar\cyrkhcrs{}", # CYRILLIC SMALL LETTER KA WITH STROKE
0x004A0: r"\cyrchar\CYRKBEAK{}", # CYRILLIC CAPITAL LETTER BASHKIR KA
0x004A1: r"\cyrchar\cyrkbeak{}", # CYRILLIC SMALL LETTER BASHKIR KA
0x004A2: r"\cyrchar\CYRNDSC{}", # CYRILLIC CAPITAL LETTER EN WITH DESCENDER
0x004A3: r"\cyrchar\cyrndsc{}", # CYRILLIC SMALL LETTER EN WITH DESCENDER
0x004A4: r"\cyrchar\CYRNG{}", # CYRILLIC CAPITAL LIGATURE EN GHE
0x004A5: r"\cyrchar\cyrng{}", # CYRILLIC SMALL LIGATURE EN GHE
0x004A6: r"\cyrchar\CYRPHK{}", # CYRILLIC CAPITAL LETTER PE WITH MIDDLE HOOK
0x004A7: r"\cyrchar\cyrphk{}", # CYRILLIC SMALL LETTER PE WITH MIDDLE HOOK
0x004A8: r"\cyrchar\CYRABHHA{}", # CYRILLIC CAPITAL LETTER ABKHASIAN HA
0x004A9: r"\cyrchar\cyrabhha{}", # CYRILLIC SMALL LETTER ABKHASIAN HA
0x004AA: r"\cyrchar\CYRSDSC{}", # CYRILLIC CAPITAL LETTER ES WITH DESCENDER
0x004AB: r"\cyrchar\cyrsdsc{}", # CYRILLIC SMALL LETTER ES WITH DESCENDER
0x004AC: r"\cyrchar\CYRTDSC{}", # CYRILLIC CAPITAL LETTER TE WITH DESCENDER
0x004AD: r"\cyrchar\cyrtdsc{}", # CYRILLIC SMALL LETTER TE WITH DESCENDER
0x004AE: r"\cyrchar\CYRY{}", # CYRILLIC CAPITAL LETTER STRAIGHT U
0x004AF: r"\cyrchar\cyry{}", # CYRILLIC SMALL LETTER STRAIGHT U
0x004B0: r"\cyrchar\CYRYHCRS{}", # CYRILLIC CAPITAL LETTER STRAIGHT U WITH STROKE
0x004B1: r"\cyrchar\cyryhcrs{}", # CYRILLIC SMALL LETTER STRAIGHT U WITH STROKE
0x004B2: r"\cyrchar\CYRHDSC{}", # CYRILLIC CAPITAL LETTER HA WITH DESCENDER
0x004B3: r"\cyrchar\cyrhdsc{}", # CYRILLIC SMALL LETTER HA WITH DESCENDER
0x004B4: r"\cyrchar\CYRTETSE{}", # CYRILLIC CAPITAL LIGATURE TE TSE
0x004B5: r"\cyrchar\cyrtetse{}", # CYRILLIC SMALL LIGATURE TE TSE
0x004B6: r"\cyrchar\CYRCHRDSC{}", # CYRILLIC CAPITAL LETTER CHE WITH DESCENDER
0x004B7: r"\cyrchar\cyrchrdsc{}", # CYRILLIC SMALL LETTER CHE WITH DESCENDER
0x004B8: r"\cyrchar\CYRCHVCRS{}", # CYRILLIC CAPITAL LETTER CHE WITH VERTICAL STROKE
0x004B9: r"\cyrchar\cyrchvcrs{}", # CYRILLIC SMALL LETTER CHE WITH VERTICAL STROKE
0x004BA: r"\cyrchar\CYRSHHA{}", # CYRILLIC CAPITAL LETTER SHHA
0x004BB: r"\cyrchar\cyrshha{}", # CYRILLIC SMALL LETTER SHHA
0x004BC: r"\cyrchar\CYRABHCH{}", # CYRILLIC CAPITAL LETTER ABKHASIAN CHE
0x004BD: r"\cyrchar\cyrabhch{}", # CYRILLIC SMALL LETTER ABKHASIAN CHE
0x004BE: r"\cyrchar\CYRABHCHDSC{}", # CYRILLIC CAPITAL LETTER ABKHASIAN CHE WITH DESCENDER
0x004BF: r"\cyrchar\cyrabhchdsc{}", # CYRILLIC SMALL LETTER ABKHASIAN CHE WITH DESCENDER
0x004C0: r"\cyrchar\CYRpalochka{}", # CYRILLIC LETTER PALOCHKA
0x004C3: r"\cyrchar\CYRKHK{}", # CYRILLIC CAPITAL LETTER KA WITH HOOK
0x004C4: r"\cyrchar\cyrkhk{}", # CYRILLIC SMALL LETTER KA WITH HOOK
0x004C7: r"\cyrchar\CYRNHK{}", # CYRILLIC CAPITAL LETTER EN WITH HOOK
0x004C8: r"\cyrchar\cyrnhk{}", # CYRILLIC SMALL LETTER EN WITH HOOK
0x004CB: r"\cyrchar\CYRCHLDSC{}", # CYRILLIC CAPITAL LETTER KHAKASSIAN CHE
0x004CC: r"\cyrchar\cyrchldsc{}", # CYRILLIC SMALL LETTER KHAKASSIAN CHE
0x004D4: r"\cyrchar\CYRAE{}", # CYRILLIC CAPITAL LIGATURE A IE
0x004D5: r"\cyrchar\cyrae{}", # CYRILLIC SMALL LIGATURE A IE
0x004D8: r"\cyrchar\CYRSCHWA{}", # CYRILLIC CAPITAL LETTER SCHWA
0x004D9: r"\cyrchar\cyrschwa{}", # CYRILLIC SMALL LETTER SCHWA
0x004E0: r"\cyrchar\CYRABHDZE{}", # CYRILLIC CAPITAL LETTER ABKHASIAN DZE
0x004E1: r"\cyrchar\cyrabhdze{}", # CYRILLIC SMALL LETTER ABKHASIAN DZE
0x004E8: r"\cyrchar\CYROTLD{}", # CYRILLIC CAPITAL LETTER BARRED O
0x004E9: r"\cyrchar\cyrotld{}", # CYRILLIC SMALL LETTER BARRED O
0x02002: r"\hspace{0.6em}", # EN SPACE
0x02003: r"\hspace{1em}", # EM SPACE
0x02004: r"\hspace{0.33em}", # THREE-PER-EM SPACE
0x02005: r"\hspace{0.25em}", # FOUR-PER-EM SPACE
0x02006: r"\hspace{0.166em}", # SIX-PER-EM SPACE
0x02007: r"\hphantom{0}", # FIGURE SPACE
0x02008: r"\hphantom{,}", # PUNCTUATION SPACE
0x02009: r"\hspace{0.167em}", # THIN SPACE
0x02010: r"-", # HYPHEN
0x02013: r"\textendash{}", # EN DASH
0x02014: r"\textemdash{}", # EM DASH
0x02015: r"\rule{1em}{1pt}", # HORIZONTAL BAR
0x02018: r"`", # LEFT SINGLE QUOTATION MARK
0x02019: r"'", # RIGHT SINGLE QUOTATION MARK
0x0201A: r",", # SINGLE LOW-9 QUOTATION MARK
0x0201C: r"\textquotedblleft{}", # LEFT DOUBLE QUOTATION MARK
0x0201D: r"\textquotedblright{}", # RIGHT DOUBLE QUOTATION MARK
0x0201E: r",,", # DOUBLE LOW-9 QUOTATION MARK
0x02020: r"\textdagger{}", # DAGGER
0x02021: r"\textdaggerdbl{}", # DOUBLE DAGGER
0x02022: r"\textbullet{}", # BULLET
0x02024: r".", # ONE DOT LEADER
0x02025: r"..", # TWO DOT LEADER
0x02026: r"\ldots{}", # HORIZONTAL ELLIPSIS
0x02030: r"\textperthousand{}", # PER MILLE SIGN
0x02031: r"\textpertenthousand{}", # PER TEN THOUSAND SIGN
0x020AC: r"\texteuro{}", # EURO
0x02116: r"\cyrchar\textnumero{}", # NUMERO SIGN
0x02122: r"\texttrademark{}", # TRADE MARK SIGN
0x0212B: r"\AA{}", # ANGSTROM SIGN

0x02190: r"$\leftarrow$", # LEFTWARDS ARROW
0x02191: r"$\uparrow$", # UPWARDS ARROW
0x02192: r"$\rightarrow$", # RIGHTWARDS ARROW
0x02193: r"$\downarrow$", # DOWNWARDS ARROW
0x02194: r"$\leftrightarrow$", # LEFT RIGHT ARROW
0x02195: r"$\updownarrow$", # UP DOWN ARROW
0x02196: r"$\nwarrow$", # NORTH WEST ARROW
0x02197: r"$\nearrow$", # NORTH EAST ARROW
0x02198: r"$\searrow$", # SOUTH EAST ARROW
0x02199: r"$\swarrow$", # SOUTH WEST ARROW
0x0219A: r"$\nleftarrow$", # LEFTWARDS ARROW WITH STROKE
0x0219B: r"$\nrightarrow$", # RIGHTWARDS ARROW WITH STROKE
0x0219C: r"$\arrowwaveright$", # LEFTWARDS WAVE ARROW
0x0219D: r"$\arrowwaveright$", # RIGHTWARDS WAVE ARROW
0x0219E: r"$\twoheadleftarrow$", # LEFTWARDS TWO HEADED ARROW
0x021A0: r"$\twoheadrightarrow$", # RIGHTWARDS TWO HEADED ARROW
0x021A2: r"$\leftarrowtail$", # LEFTWARDS ARROW WITH TAIL
0x021A3: r"$\rightarrowtail$", # RIGHTWARDS ARROW WITH TAIL
0x021A6: r"$\mapsto$", # RIGHTWARDS ARROW FROM BAR
0x021A9: r"$\hookleftarrow$", # LEFTWARDS ARROW WITH HOOK
0x021AA: r"$\hookrightarrow$", # RIGHTWARDS ARROW WITH HOOK
0x021AB: r"$\looparrowleft$", # LEFTWARDS ARROW WITH LOOP
0x021AC: r"$\looparrowright$", # RIGHTWARDS ARROW WITH LOOP
0x021AD: r"$\leftrightsquigarrow$", # LEFT RIGHT WAVE ARROW
0x021AE: r"$\nleftrightarrow$", # LEFT RIGHT ARROW WITH STROKE
0x021B0: r"$\Lsh$", # UPWARDS ARROW WITH TIP LEFTWARDS
0x021B1: r"$\Rsh$", # UPWARDS ARROW WITH TIP RIGHTWARDS
0x021B3: r"$\ElsevierGlyph{21B3}$", # DOWNWARDS ARROW WITH TIP RIGHTWARDS
0x021B6: r"$\curvearrowleft$", # ANTICLOCKWISE TOP SEMICIRCLE ARROW
0x021B7: r"$\curvearrowright$", # CLOCKWISE TOP SEMICIRCLE ARROW
0x021BA: r"$\circlearrowleft$", # ANTICLOCKWISE OPEN CIRCLE ARROW
0x021BB: r"$\circlearrowright$", # CLOCKWISE OPEN CIRCLE ARROW
0x021BC: r"$\leftharpoonup$", # LEFTWARDS HARPOON WITH BARB UPWARDS
0x021BD: r"$\leftharpoondown$", # LEFTWARDS HARPOON WITH BARB DOWNWARDS
0x021BE: r"$\upharpoonright$", # UPWARDS HARPOON WITH BARB RIGHTWARDS
0x021BF: r"$\upharpoonleft$", # UPWARDS HARPOON WITH BARB LEFTWARDS
0x021C0: r"$\rightharpoonup$", # RIGHTWARDS HARPOON WITH BARB UPWARDS
0x021C1: r"$\rightharpoondown$", # RIGHTWARDS HARPOON WITH BARB DOWNWARDS
0x021C2: r"$\downharpoonright$", # DOWNWARDS HARPOON WITH BARB RIGHTWARDS
0x021C3: r"$\downharpoonleft$", # DOWNWARDS HARPOON WITH BARB LEFTWARDS
0x021C4: r"$\rightleftarrows$", # RIGHTWARDS ARROW OVER LEFTWARDS ARROW
0x021C5: r"$\dblarrowupdown$", # UPWARDS ARROW LEFTWARDS OF DOWNWARDS ARROW
0x021C6: r"$\leftrightarrows$", # LEFTWARDS ARROW OVER RIGHTWARDS ARROW
0x021C7: r"$\leftleftarrows$", # LEFTWARDS PAIRED ARROWS
0x021C8: r"$\upuparrows$", # UPWARDS PAIRED ARROWS
0x021C9: r"$\rightrightarrows$", # RIGHTWARDS PAIRED ARROWS
0x021CA: r"$\downdownarrows$", # DOWNWARDS PAIRED ARROWS
0x021CB: r"$\leftrightharpoons$", # LEFTWARDS HARPOON OVER RIGHTWARDS HARPOON
0x021CC: r"$\rightleftharpoons$", # RIGHTWARDS HARPOON OVER LEFTWARDS HARPOON
0x021CD: r"$\nLeftarrow$", # LEFTWARDS DOUBLE ARROW WITH STROKE
0x021CE: r"$\nLeftrightarrow$", # LEFT RIGHT DOUBLE ARROW WITH STROKE
0x021CF: r"$\nRightarrow$", # RIGHTWARDS DOUBLE ARROW WITH STROKE
0x021D0: r"$\Leftarrow$", # LEFTWARDS DOUBLE ARROW
0x021D1: r"$\Uparrow$", # UPWARDS DOUBLE ARROW
0x021D2: r"$\Rightarrow$", # RIGHTWARDS DOUBLE ARROW
0x021D3: r"$\Downarrow$", # DOWNWARDS DOUBLE ARROW
0x021D4: r"$\Leftrightarrow$", # LEFT RIGHT DOUBLE ARROW
0x021D5: r"$\Updownarrow$", # UP DOWN DOUBLE ARROW
0x021DA: r"$\Lleftarrow$", # LEFTWARDS TRIPLE ARROW
0x021DB: r"$\Rrightarrow$", # RIGHTWARDS TRIPLE ARROW
0x021DD: r"$\rightsquigarrow$", # RIGHTWARDS SQUIGGLE ARROW
0x021F5: r"$\DownArrowUpArrow$", # DOWNWARDS ARROW LEFTWARDS OF UPWARDS ARROW
0x02200: r"$\forall$", # FOR ALL
0x02201: r"$\complement$", # COMPLEMENT
0x02202: r"$\partial$", # PARTIAL DIFFERENTIAL
0x02203: r"$\exists$", # THERE EXISTS
0x02204: r"$\nexists$", # THERE DOES NOT EXIST
0x02205: r"$\varnothing$", # EMPTY SET
0x02207: r"$\nabla$", # NABLA
0x02208: r"$\in$", # ELEMENT OF
0x02209: r"$\not\in$", # NOT AN ELEMENT OF
0x0220B: r"$\ni$", # CONTAINS AS MEMBER
0x0220C: r"$\not\ni$", # DOES NOT CONTAIN AS MEMBER
0x0220F: r"$\prod$", # N-ARY PRODUCT
0x02210: r"$\coprod$", # N-ARY COPRODUCT
0x02211: r"$\sum$", # N-ARY SUMMATION
0x02212: r"-", # MINUS SIGN
0x02213: r"$\mp$", # MINUS-OR-PLUS SIGN
0x02214: r"$\dotplus$", # DOT PLUS
0x02216: r"$\setminus$", # SET MINUS
0x02217: r"${_\ast}$", # ASTERISK OPERATOR
0x02218: r"$\circ$", # RING OPERATOR
0x02219: r"$\bullet$", # BULLET OPERATOR
0x0221A: r"$\surd$", # SQUARE ROOT
0x0221D: r"$\propto$", # PROPORTIONAL TO
0x0221E: r"$\infty$", # INFINITY
0x0221F: r"$\rightangle$", # RIGHT ANGLE
0x02220: r"$\angle$", # ANGLE
0x02221: r"$\measuredangle$", # MEASURED ANGLE
0x02222: r"$\sphericalangle$", # SPHERICAL ANGLE
0x02223: r"$\mid$", # DIVIDES
0x02224: r"$\nmid$", # DOES NOT DIVIDE
0x02225: r"$\parallel$", # PARALLEL TO
0x02226: r"$\nparallel$", # NOT PARALLEL TO
0x02227: r"$\wedge$", # LOGICAL AND
0x02228: r"$\vee$", # LOGICAL OR
0x02229: r"$\cap$", # INTERSECTION
0x0222A: r"$\cup$", # UNION
0x0222B: r"$\int$", # INTEGRAL
0x0222C: r"$\int\!\int$", # DOUBLE INTEGRAL
0x0222D: r"$\int\!\int\!\int$", # TRIPLE INTEGRAL
0x0222E: r"$\oint$", # CONTOUR INTEGRAL
0x0222F: r"$\surfintegral$", # SURFACE INTEGRAL
0x02230: r"$\volintegral$", # VOLUME INTEGRAL
0x02231: r"$\clwintegral$", # CLOCKWISE INTEGRAL
0x02232: r"$\ElsevierGlyph{2232}$", # CLOCKWISE CONTOUR INTEGRAL
0x02233: r"$\ElsevierGlyph{2233}$", # ANTICLOCKWISE CONTOUR INTEGRAL
0x02234: r"$\therefore$", # THEREFORE
0x02235: r"$\because$", # BECAUSE
0x02237: r"$\Colon$", # PROPORTION
0x02238: r"$\ElsevierGlyph{2238}$", # DOT MINUS
0x0223A: r"$\mathbin{{:}\!\!{-}\!\!{:}}$", # GEOMETRIC PROPORTION
0x0223B: r"$\homothetic$", # HOMOTHETIC
0x0223C: r"$\sim$", # TILDE OPERATOR
0x0223D: r"$\backsim$", # REVERSED TILDE
0x0223E: r"$\lazysinv$", # INVERTED LAZY S
0x02240: r"$\wr$", # WREATH PRODUCT
0x02241: r"$\not\sim$", # NOT TILDE
0x02242: r"$\ElsevierGlyph{2242}$", # MINUS TILDE
0x02243: r"$\simeq$", # ASYMPTOTICALLY EQUAL TO
0x02244: r"$\not\simeq$", # NOT ASYMPTOTICALLY EQUAL TO
0x02245: r"$\cong$", # APPROXIMATELY EQUAL TO
0x02246: r"$\approxnotequal$", # APPROXIMATELY BUT NOT ACTUALLY EQUAL TO
0x02247: r"$\not\cong$", # NEITHER APPROXIMATELY NOR ACTUALLY EQUAL TO
0x02248: r"$\approx$", # ALMOST EQUAL TO
0x02249: r"$\not\approx$", # NOT ALMOST EQUAL TO
0x0224A: r"$\approxeq$", # ALMOST EQUAL OR EQUAL TO
0x0224B: r"$\tildetrpl$", # TRIPLE TILDE
0x0224C: r"$\allequal$", # ALL EQUAL TO
0x0224D: r"$\asymp$", # EQUIVALENT TO
0x0224E: r"$\Bumpeq$", # GEOMETRICALLY EQUIVALENT TO
0x0224F: r"$\bumpeq$", # DIFFERENCE BETWEEN
0x02250: r"$\doteq$", # APPROACHES THE LIMIT
0x02251: r"$\doteqdot$", # GEOMETRICALLY EQUAL TO
0x02252: r"$\fallingdotseq$", # APPROXIMATELY EQUAL TO OR THE IMAGE OF
0x02253: r"$\risingdotseq$", # IMAGE OF OR APPROXIMATELY EQUAL TO
0x02254: r":=", # COLON EQUALS
0x02260: r"$\neq$", # NOT EQUAL TO
0x02261: r"$\equiv$", # IDENTICAL TO
0x02262: r"$\not\equiv$", # NOT IDENTICAL TO
0x02264: r"$\leq$", # LESS-THAN OR EQUAL TO
0x02265: r"$\geq$", # GREATER-THAN OR EQUAL TO
0x02266: r"$\leqq$", # LESS-THAN OVER EQUAL TO
0x02267: r"$\geqq$", # GREATER-THAN OVER EQUAL TO
0x02268: r"$\lneqq$", # LESS-THAN BUT NOT EQUAL TO
0x02269: r"$\gneqq$", # GREATER-THAN BUT NOT EQUAL TO
0x0226A: r"$\ll$", # MUCH LESS-THAN
0x0226B: r"$\gg$", # MUCH GREATER-THAN
0x0226C: r"$\between$", # BETWEEN
0x0226D: r"$\not\kern-0.3em\times$", # NOT EQUIVALENT TO
0x0226E: r"$\not<$", # NOT LESS-THAN
0x0226F: r"$\not>$", # NOT GREATER-THAN
0x02270: r"$\not\leq$", # NEITHER LESS-THAN NOR EQUAL TO
0x02271: r"$\not\geq$", # NEITHER GREATER-THAN NOR EQUAL TO
0x02272: r"$\lessequivlnt$", # LESS-THAN OR EQUIVALENT TO
0x02273: r"$\greaterequivlnt$", # GREATER-THAN OR EQUIVALENT TO
0x02274: r"$\ElsevierGlyph{2274}$", # NEITHER LESS-THAN NOR EQUIVALENT TO
0x02275: r"$\ElsevierGlyph{2275}$", # NEITHER GREATER-THAN NOR EQUIVALENT TO
0x02276: r"$\lessgtr$", # LESS-THAN OR GREATER-THAN
0x02277: r"$\gtrless$", # GREATER-THAN OR LESS-THAN
0x02278: r"$\notlessgreater$", # NEITHER LESS-THAN NOR GREATER-THAN
0x02279: r"$\notgreaterless$", # NEITHER GREATER-THAN NOR LESS-THAN
0x0227A: r"$\prec$", # PRECEDES
0x0227B: r"$\succ$", # SUCCEEDS
0x0227C: r"$\preccurlyeq$", # PRECEDES OR EQUAL TO
0x0227D: r"$\succcurlyeq$", # SUCCEEDS OR EQUAL TO
0x0227E: r"$\precapprox$", # PRECEDES OR EQUIVALENT TO
0x0227F: r"$\succapprox$", # SUCCEEDS OR EQUIVALENT TO
0x02280: r"$\not\prec$", # DOES NOT PRECEDE
0x02281: r"$\not\succ$", # DOES NOT SUCCEED
0x02282: r"$\subset$", # SUBSET OF
0x02283: r"$\supset$", # SUPERSET OF
0x02284: r"$\not\subset$", # NOT A SUBSET OF
0x02285: r"$\not\supset$", # NOT A SUPERSET OF
0x02286: r"$\subseteq$", # SUBSET OF OR EQUAL TO
0x02287: r"$\supseteq$", # SUPERSET OF OR EQUAL TO
0x02288: r"$\not\subseteq$", # NEITHER A SUBSET OF NOR EQUAL TO
0x02289: r"$\not\supseteq$", # NEITHER A SUPERSET OF NOR EQUAL TO
0x0228A: r"$\subsetneq$", # SUBSET OF WITH NOT EQUAL TO
0x0228B: r"$\supsetneq$", # SUPERSET OF WITH NOT EQUAL TO
0x0228E: r"$\uplus$", # MULTISET UNION
0x0228F: r"$\sqsubset$", # SQUARE IMAGE OF
0x02290: r"$\sqsupset$", # SQUARE ORIGINAL OF
0x02291: r"$\sqsubseteq$", # SQUARE IMAGE OF OR EQUAL TO
0x02292: r"$\sqsupseteq$", # SQUARE ORIGINAL OF OR EQUAL TO
0x02293: r"$\sqcap$", # SQUARE CAP
0x02294: r"$\sqcup$", # SQUARE CUP
0x02295: r"$\oplus$", # CIRCLED PLUS
0x02296: r"$\ominus$", # CIRCLED MINUS
0x02297: r"$\otimes$", # CIRCLED TIMES
0x02298: r"$\oslash$", # CIRCLED DIVISION SLASH
0x02299: r"$\odot$", # CIRCLED DOT OPERATOR
0x0229A: r"$\circledcirc$", # CIRCLED RING OPERATOR
0x0229B: r"$\circledast$", # CIRCLED ASTERISK OPERATOR
0x0229D: r"$\circleddash$", # CIRCLED DASH
0x0229E: r"$\boxplus$", # SQUARED PLUS
0x0229F: r"$\boxminus$", # SQUARED MINUS
0x022A0: r"$\boxtimes$", # SQUARED TIMES
0x022A1: r"$\boxdot$", # SQUARED DOT OPERATOR
0x022A2: r"$\vdash$", # RIGHT TACK
0x022A3: r"$\dashv$", # LEFT TACK
0x022A4: r"$\top$", # DOWN TACK
0x022A5: r"$\perp$", # UP TACK
0x022A7: r"$\truestate$", # MODELS
0x022A8: r"$\forcesextra$", # TRUE
0x022A9: r"$\Vdash$", # FORCES
0x022AA: r"$\Vvdash$", # TRIPLE VERTICAL BAR RIGHT TURNSTILE
0x022AB: r"$\VDash$", # DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE
0x022AC: r"$\nvdash$", # DOES NOT PROVE
0x022AD: r"$\nvDash$", # NOT TRUE
0x022AE: r"$\nVdash$", # DOES NOT FORCE
0x022AF: r"$\nVDash$", # NEGATED DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE
0x022B2: r"$\vartriangleleft$", # NORMAL SUBGROUP OF
0x022B3: r"$\vartriangleright$", # CONTAINS AS NORMAL SUBGROUP
0x022B4: r"$\trianglelefteq$", # NORMAL SUBGROUP OF OR EQUAL TO
0x022B5: r"$\trianglerighteq$", # CONTAINS AS NORMAL SUBGROUP OR EQUAL TO
0x022B6: r"$\original$", # ORIGINAL OF
0x022B7: r"$\image$", # IMAGE OF
0x022B8: r"$\multimap$", # MULTIMAP
0x022B9: r"$\hermitconjmatrix$", # HERMITIAN CONJUGATE MATRIX
0x022BA: r"$\intercal$", # INTERCALATE
0x022BB: r"$\veebar$", # XOR
0x022BE: r"$\rightanglearc$", # RIGHT ANGLE WITH ARC
0x022C0: r"$\ElsevierGlyph{22C0}$", # N-ARY LOGICAL AND
0x022C1: r"$\ElsevierGlyph{22C1}$", # N-ARY LOGICAL OR
0x022C2: r"$\bigcap$", # N-ARY INTERSECTION
0x022C3: r"$\bigcup$", # N-ARY UNION
0x022C4: r"$\diamond$", # DIAMOND OPERATOR
0x022C5: r"$\cdot$", # DOT OPERATOR
0x022C6: r"$\star$", # STAR OPERATOR
0x022C7: r"$\divideontimes$", # DIVISION TIMES
0x022C8: r"$\bowtie$", # BOWTIE
0x022C9: r"$\ltimes$", # LEFT NORMAL FACTOR SEMIDIRECT PRODUCT
0x022CA: r"$\rtimes$", # RIGHT NORMAL FACTOR SEMIDIRECT PRODUCT
0x022CB: r"$\leftthreetimes$", # LEFT SEMIDIRECT PRODUCT
0x022CC: r"$\rightthreetimes$", # RIGHT SEMIDIRECT PRODUCT
0x022CD: r"$\backsimeq$", # REVERSED TILDE EQUALS
0x022CE: r"$\curlyvee$", # CURLY LOGICAL OR
0x022CF: r"$\curlywedge$", # CURLY LOGICAL AND
0x022D0: r"$\Subset$", # DOUBLE SUBSET
0x022D1: r"$\Supset$", # DOUBLE SUPERSET
0x022D2: r"$\Cap$", # DOUBLE INTERSECTION
0x022D3: r"$\Cup$", # DOUBLE UNION
0x022D4: r"$\pitchfork$", # PITCHFORK
0x022D6: r"$\lessdot$", # LESS-THAN WITH DOT
0x022D7: r"$\gtrdot$", # GREATER-THAN WITH DOT
0x022D8: r"$\verymuchless$", # VERY MUCH LESS-THAN
0x022D9: r"$\verymuchgreater$", # VERY MUCH GREATER-THAN
0x022DA: r"$\lesseqgtr$", # LESS-THAN EQUAL TO OR GREATER-THAN
0x022DB: r"$\gtreqless$", # GREATER-THAN EQUAL TO OR LESS-THAN
0x022DE: r"$\curlyeqprec$", # EQUAL TO OR PRECEDES
0x022DF: r"$\curlyeqsucc$", # EQUAL TO OR SUCCEEDS
0x022E2: r"$\not\sqsubseteq$", # NOT SQUARE IMAGE OF OR EQUAL TO
0x022E3: r"$\not\sqsupseteq$", # NOT SQUARE ORIGINAL OF OR EQUAL TO
0x022E5: r"$\Elzsqspne$", # SQUARE ORIGINAL OF OR NOT EQUAL TO
0x022E6: r"$\lnsim$", # LESS-THAN BUT NOT EQUIVALENT TO
0x022E7: r"$\gnsim$", # GREATER-THAN BUT NOT EQUIVALENT TO
0x022E8: r"$\precedesnotsimilar$", # PRECEDES BUT NOT EQUIVALENT TO
0x022E9: r"$\succnsim$", # SUCCEEDS BUT NOT EQUIVALENT TO
0x022EA: r"$\ntriangleleft$", # NOT NORMAL SUBGROUP OF
0x022EB: r"$\ntriangleright$", # DOES NOT CONTAIN AS NORMAL SUBGROUP
0x022EC: r"$\ntrianglelefteq$", # NOT NORMAL SUBGROUP OF OR EQUAL TO
0x022ED: r"$\ntrianglerighteq$", # DOES NOT CONTAIN AS NORMAL SUBGROUP OR EQUAL
0x022EE: r"$\vdots$", # VERTICAL ELLIPSIS
0x022EF: r"$\cdots$", # MIDLINE HORIZONTAL ELLIPSIS
0x022F0: r"$\upslopeellipsis$", # UP RIGHT DIAGONAL ELLIPSIS
0x022F1: r"$\downslopeellipsis$", # DOWN RIGHT DIAGONAL ELLIPSIS
0x02306: r"$\perspcorrespond$", # PERSPECTIVE
0x02308: r"$\lceil$", # LEFT CEILING
0x02309: r"$\rceil$", # RIGHT CEILING
0x0230A: r"$\lfloor$", # LEFT FLOOR
0x0230B: r"$\rfloor$", # RIGHT FLOOR

0x02315: r"$\recorder$", # TELEPHONE RECORDER
0x02316: r'$\mathchar"2208$', # POSITION INDICATOR
0x0231C: r"$\ulcorner$", # TOP LEFT CORNER
0x0231D: r"$\urcorner$", # TOP RIGHT CORNER
0x0231E: r"$\llcorner$", # BOTTOM LEFT CORNER
0x0231F: r"$\lrcorner$", # BOTTOM RIGHT CORNER
0x02322: r"$\frown$", # FROWN
0x02323: r"$\smile$", # SMILE
0x02329: r"$\langle$", # LEFT-POINTING ANGLE BRACKET
0x0232A: r"$\rangle$", # RIGHT-POINTING ANGLE BRACKET
0x0233D: r"$\ElsevierGlyph{E838}$", # APL FUNCTIONAL SYMBOL CIRCLE STILE
0x023A3: r"$\Elzdlcorn$", # LEFT SQUARE BRACKET LOWER CORNER
0x023B0: r"$\lmoustache$", # UPPER LEFT OR LOWER RIGHT CURLY BRACKET SECTION
0x023B1: r"$\rmoustache$", # UPPER RIGHT OR LOWER LEFT CURLY BRACKET SECTION
0x02423: r"\textvisiblespace{}", # OPEN BOX
0x02460: r"\ding{172}", # CIRCLED DIGIT ONE
0x02461: r"\ding{173}", # CIRCLED DIGIT TWO
0x02462: r"\ding{174}", # CIRCLED DIGIT THREE
0x02463: r"\ding{175}", # CIRCLED DIGIT FOUR
0x02464: r"\ding{176}", # CIRCLED DIGIT FIVE
0x02465: r"\ding{177}", # CIRCLED DIGIT SIX
0x02466: r"\ding{178}", # CIRCLED DIGIT SEVEN
0x02467: r"\ding{179}", # CIRCLED DIGIT EIGHT
0x02468: r"\ding{180}", # CIRCLED DIGIT NINE
0x02469: r"\ding{181}", # CIRCLED NUMBER TEN
0x025A0: r"\ding{110}", # BLACK SQUARE
0x025A1: r"$\square$", # WHITE SQUARE
0x025AA: r"$\blacksquare$", # BLACK SMALL SQUARE
0x025AD: r"\fbox{~~}", # WHITE RECTANGLE
0x025AF: r"$\Elzvrecto$", # WHITE VERTICAL RECTANGLE
0x025B1: r"$\ElsevierGlyph{E381}$", # WHITE PARALLELOGRAM
0x025B2: r"\ding{115}", # BLACK UP-POINTING TRIANGLE
0x025B3: r"$\bigtriangleup$", # WHITE UP-POINTING TRIANGLE
0x025B4: r"$\blacktriangle$", # BLACK UP-POINTING SMALL TRIANGLE
0x025B5: r"$\vartriangle$", # WHITE UP-POINTING SMALL TRIANGLE
0x025B8: r"$\blacktriangleright$", # BLACK RIGHT-POINTING SMALL TRIANGLE
0x025B9: r"$\triangleright$", # WHITE RIGHT-POINTING SMALL TRIANGLE
0x025BC: r"\ding{116}", # BLACK DOWN-POINTING TRIANGLE
0x025BD: r"$\bigtriangledown$", # WHITE DOWN-POINTING TRIANGLE
0x025BE: r"$\blacktriangledown$", # BLACK DOWN-POINTING SMALL TRIANGLE
0x025BF: r"$\triangledown$", # WHITE DOWN-POINTING SMALL TRIANGLE
0x025C2: r"$\blacktriangleleft$", # BLACK LEFT-POINTING SMALL TRIANGLE
0x025C3: r"$\triangleleft$", # WHITE LEFT-POINTING SMALL TRIANGLE
0x025C6: r"\ding{117}", # BLACK DIAMOND
0x025CA: r"$\lozenge$", # LOZENGE
0x025CB: r"$\bigcirc$", # WHITE CIRCLE
0x025CF: r"\ding{108}", # BLACK CIRCLE
0x025D7: r"\ding{119}", # RIGHT HALF BLACK CIRCLE
0x02605: r"\ding{72}", # BLACK STAR
0x0260E: r"\ding{37}", # BLACK TELEPHONE
0x0261B: r"\ding{42}", # BLACK RIGHT POINTING INDEX
0x0261E: r"\ding{43}", # WHITE RIGHT POINTING INDEX
0x02640: r"\venus{}", # FEMALE SIGN
0x02642: r"\male{}", # MALE SIGN
0x02647: r"\pluto{}", # PLUTO
0x02648: r"\aries{}", # ARIES
0x02649: r"\taurus{}", # TAURUS
0x0264A: r"\gemini{}", # GEMINI
0x0264B: r"\cancer{}", # CANCER
0x0264C: r"\leo{}", # LEO
0x0264D: r"\virgo{}", # VIRGO
0x0264E: r"\libra{}", # LIBRA
0x0264F: r"\scorpio{}", # SCORPIUS
0x02650: r"\sagittarius{}", # SAGITTARIUS
0x02651: r"\capricornus{}", # CAPRICORN
0x02652: r"\aquarius{}", # AQUARIUS
0x02653: r"\pisces{}", # PISCES
0x02660: r"\ding{171}", # BLACK SPADE SUIT
0x02663: r"\ding{168}", # BLACK CLUB SUIT
0x02665: r"\ding{170}", # BLACK HEART SUIT
0x02666: r"\ding{169}", # BLACK DIAMOND SUIT
0x02669: r"\quarternote{}", # QUARTER NOTE
0x0266A: r"\eighthnote{}", # EIGHTH NOTE
0x02701: r"\ding{33}", # UPPER BLADE SCISSORS
0x02702: r"\ding{34}", # BLACK SCISSORS
0x02703: r"\ding{35}", # LOWER BLADE SCISSORS
0x02704: r"\ding{36}", # WHITE SCISSORS
0x02706: r"\ding{38}", # TELEPHONE LOCATION SIGN
0x02707: r"\ding{39}", # TAPE DRIVE
0x02708: r"\ding{40}", # AIRPLANE
0x02709: r"\ding{41}", # ENVELOPE
0x0270C: r"\ding{44}", # VICTORY HAND
0x0270D: r"\ding{45}", # WRITING HAND
0x0270E: r"\ding{46}", # LOWER RIGHT PENCIL
0x0270F: r"\ding{47}", # PENCIL
0x02710: r"\ding{48}", # UPPER RIGHT PENCIL
0x02711: r"\ding{49}", # WHITE NIB
0x02712: r"\ding{50}", # BLACK NIB
0x02713: r"\ding{51}", # CHECK MARK
0x02714: r"\ding{52}", # HEAVY CHECK MARK
0x02715: r"\ding{53}", # MULTIPLICATION X
0x02716: r"\ding{54}", # HEAVY MULTIPLICATION X
0x02717: r"\ding{55}", # BALLOT X
0x02718: r"\ding{56}", # HEAVY BALLOT X
0x02719: r"\ding{57}", # OUTLINED GREEK CROSS
0x0271A: r"\ding{58}", # HEAVY GREEK CROSS
0x0271B: r"\ding{59}", # OPEN CENTRE CROSS
0x0271C: r"\ding{60}", # HEAVY OPEN CENTRE CROSS
0x0271D: r"\ding{61}", # LATIN CROSS
0x0271E: r"\ding{62}", # SHADOWED WHITE LATIN CROSS
0x0271F: r"\ding{63}", # OUTLINED LATIN CROSS
0x02720: r"\ding{64}", # MALTESE CROSS
0x02721: r"\ding{65}", # STAR OF DAVID
0x02722: r"\ding{66}", # FOUR TEARDROP-SPOKED ASTERISK
0x02723: r"\ding{67}", # FOUR BALLOON-SPOKED ASTERISK
0x02724: r"\ding{68}", # HEAVY FOUR BALLOON-SPOKED ASTERISK
0x02725: r"\ding{69}", # FOUR CLUB-SPOKED ASTERISK
0x02726: r"\ding{70}", # BLACK FOUR POINTED STAR
0x02727: r"\ding{71}", # WHITE FOUR POINTED STAR
0x02729: r"\ding{73}", # STRESS OUTLINED WHITE STAR
0x0272A: r"\ding{74}", # CIRCLED WHITE STAR
0x0272B: r"\ding{75}", # OPEN CENTRE BLACK STAR
0x0272C: r"\ding{76}", # BLACK CENTRE WHITE STAR
0x0272D: r"\ding{77}", # OUTLINED BLACK STAR
0x0272E: r"\ding{78}", # HEAVY OUTLINED BLACK STAR
0x0272F: r"\ding{79}", # PINWHEEL STAR
0x02730: r"\ding{80}", # SHADOWED WHITE STAR
0x02731: r"\ding{81}", # HEAVY ASTERISK
0x02732: r"\ding{82}", # OPEN CENTRE ASTERISK
0x02733: r"\ding{83}", # EIGHT SPOKED ASTERISK
0x02734: r"\ding{84}", # EIGHT POINTED BLACK STAR
0x02735: r"\ding{85}", # EIGHT POINTED PINWHEEL STAR
0x02736: r"\ding{86}", # SIX POINTED BLACK STAR
0x02737: r"\ding{87}", # EIGHT POINTED RECTILINEAR BLACK STAR
0x02738: r"\ding{88}", # HEAVY EIGHT POINTED RECTILINEAR BLACK STAR
0x02739: r"\ding{89}", # TWELVE POINTED BLACK STAR
0x0273A: r"\ding{90}", # SIXTEEN POINTED ASTERISK
0x0273B: r"\ding{91}", # TEARDROP-SPOKED ASTERISK
0x0273C: r"\ding{92}", # OPEN CENTRE TEARDROP-SPOKED ASTERISK
0x0273D: r"\ding{93}", # HEAVY TEARDROP-SPOKED ASTERISK
0x0273E: r"\ding{94}", # SIX PETALLED BLACK AND WHITE FLORETTE
0x0273F: r"\ding{95}", # BLACK FLORETTE
0x02740: r"\ding{96}", # WHITE FLORETTE
0x02741: r"\ding{97}", # EIGHT PETALLED OUTLINED BLACK FLORETTE
0x02742: r"\ding{98}", # CIRCLED OPEN CENTRE EIGHT POINTED STAR
0x02743: r"\ding{99}", # HEAVY TEARDROP-SPOKED PINWHEEL ASTERISK
0x02744: r"\ding{100}", # SNOWFLAKE
0x02745: r"\ding{101}", # TIGHT TRIFOLIATE SNOWFLAKE
0x02746: r"\ding{102}", # HEAVY CHEVRON SNOWFLAKE
0x02747: r"\ding{103}", # SPARKLE
0x02748: r"\ding{104}", # HEAVY SPARKLE
0x02749: r"\ding{105}", # BALLOON-SPOKED ASTERISK
0x0274A: r"\ding{106}", # EIGHT TEARDROP-SPOKED PROPELLER ASTERISK
0x0274B: r"\ding{107}", # HEAVY EIGHT TEARDROP-SPOKED PROPELLER ASTERISK
0x0274D: r"\ding{109}", # SHADOWED WHITE CIRCLE
0x0274F: r"\ding{111}", # LOWER RIGHT DROP-SHADOWED WHITE SQUARE
0x02750: r"\ding{112}", # UPPER RIGHT DROP-SHADOWED WHITE SQUARE
0x02751: r"\ding{113}", # LOWER RIGHT SHADOWED WHITE SQUARE
0x02752: r"\ding{114}", # UPPER RIGHT SHADOWED WHITE SQUARE
0x02756: r"\ding{118}", # BLACK DIAMOND MINUS WHITE X
0x02758: r"\ding{120}", # LIGHT VERTICAL BAR
0x02759: r"\ding{121}", # MEDIUM VERTICAL BAR
0x0275A: r"\ding{122}", # HEAVY VERTICAL BAR
0x0275B: r"\ding{123}", # HEAVY SINGLE TURNED COMMA QUOTATION MARK ORNAMENT
0x0275C: r"\ding{124}", # HEAVY SINGLE COMMA QUOTATION MARK ORNAMENT
0x0275D: r"\ding{125}", # HEAVY DOUBLE TURNED COMMA QUOTATION MARK ORNAMENT
0x0275E: r"\ding{126}", # HEAVY DOUBLE COMMA QUOTATION MARK ORNAMENT
0x02761: r"\ding{161}", # CURVED STEM PARAGRAPH SIGN ORNAMENT
0x02762: r"\ding{162}", # HEAVY EXCLAMATION MARK ORNAMENT
0x02763: r"\ding{163}", # HEAVY HEART EXCLAMATION MARK ORNAMENT
0x02764: r"\ding{164}", # HEAVY BLACK HEART
0x02765: r"\ding{165}", # ROTATED HEAVY BLACK HEART BULLET
0x02766: r"\ding{166}", # FLORAL HEART
0x02767: r"\ding{167}", # ROTATED FLORAL HEART BULLET
0x02776: r"\ding{182}", # DINGBAT NEGATIVE CIRCLED DIGIT ONE
0x02777: r"\ding{183}", # DINGBAT NEGATIVE CIRCLED DIGIT TWO
0x02778: r"\ding{184}", # DINGBAT NEGATIVE CIRCLED DIGIT THREE
0x02779: r"\ding{185}", # DINGBAT NEGATIVE CIRCLED DIGIT FOUR
0x0277A: r"\ding{186}", # DINGBAT NEGATIVE CIRCLED DIGIT FIVE
0x0277B: r"\ding{187}", # DINGBAT NEGATIVE CIRCLED DIGIT SIX
0x0277C: r"\ding{188}", # DINGBAT NEGATIVE CIRCLED DIGIT SEVEN
0x0277D: r"\ding{189}", # DINGBAT NEGATIVE CIRCLED DIGIT EIGHT
0x0277E: r"\ding{190}", # DINGBAT NEGATIVE CIRCLED DIGIT NINE
0x0277F: r"\ding{191}", # DINGBAT NEGATIVE CIRCLED NUMBER TEN
0x02780: r"\ding{192}", # DINGBAT CIRCLED SANS-SERIF DIGIT ONE
0x02781: r"\ding{193}", # DINGBAT CIRCLED SANS-SERIF DIGIT TWO
0x02782: r"\ding{194}", # DINGBAT CIRCLED SANS-SERIF DIGIT THREE
0x02783: r"\ding{195}", # DINGBAT CIRCLED SANS-SERIF DIGIT FOUR
0x02784: r"\ding{196}", # DINGBAT CIRCLED SANS-SERIF DIGIT FIVE
0x02785: r"\ding{197}", # DINGBAT CIRCLED SANS-SERIF DIGIT SIX
0x02786: r"\ding{198}", # DINGBAT CIRCLED SANS-SERIF DIGIT SEVEN
0x02787: r"\ding{199}", # DINGBAT CIRCLED SANS-SERIF DIGIT EIGHT
0x02788: r"\ding{200}", # DINGBAT CIRCLED SANS-SERIF DIGIT NINE
0x02789: r"\ding{201}", # DINGBAT CIRCLED SANS-SERIF NUMBER TEN
0x0278A: r"\ding{202}", # DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT ONE
0x0278B: r"\ding{203}", # DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT TWO
0x0278C: r"\ding{204}", # DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT THREE
0x0278D: r"\ding{205}", # DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT FOUR
0x0278E: r"\ding{206}", # DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT FIVE
0x0278F: r"\ding{207}", # DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT SIX
0x02790: r"\ding{208}", # DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT SEVEN
0x02791: r"\ding{209}", # DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT EIGHT
0x02792: r"\ding{210}", # DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT NINE
0x02793: r"\ding{211}", # DINGBAT NEGATIVE CIRCLED SANS-SERIF NUMBER TEN
0x02794: r"\ding{212}", # HEAVY WIDE-HEADED RIGHTWARDS ARROW
0x02798: r"\ding{216}", # HEAVY SOUTH EAST ARROW
0x02799: r"\ding{217}", # HEAVY RIGHTWARDS ARROW
0x0279A: r"\ding{218}", # HEAVY NORTH EAST ARROW
0x0279B: r"\ding{219}", # DRAFTING POINT RIGHTWARDS ARROW
0x0279C: r"\ding{220}", # HEAVY ROUND-TIPPED RIGHTWARDS ARROW
0x0279D: r"\ding{221}", # TRIANGLE-HEADED RIGHTWARDS ARROW
0x0279E: r"\ding{222}", # HEAVY TRIANGLE-HEADED RIGHTWARDS ARROW
0x0279F: r"\ding{223}", # DASHED TRIANGLE-HEADED RIGHTWARDS ARROW
0x027A0: r"\ding{224}", # HEAVY DASHED TRIANGLE-HEADED RIGHTWARDS ARROW
0x027A1: r"\ding{225}", # BLACK RIGHTWARDS ARROW
0x027A2: r"\ding{226}", # THREE-D TOP-LIGHTED RIGHTWARDS ARROWHEAD
0x027A3: r"\ding{227}", # THREE-D BOTTOM-LIGHTED RIGHTWARDS ARROWHEAD
0x027A4: r"\ding{228}", # BLACK RIGHTWARDS ARROWHEAD
0x027A5: r"\ding{229}", # HEAVY BLACK CURVED DOWNWARDS AND RIGHTWARDS ARROW
0x027A6: r"\ding{230}", # HEAVY BLACK CURVED UPWARDS AND RIGHTWARDS ARROW
0x027A7: r"\ding{231}", # SQUAT BLACK RIGHTWARDS ARROW
0x027A8: r"\ding{232}", # HEAVY CONCAVE-POINTED BLACK RIGHTWARDS ARROW
0x027A9: r"\ding{233}", # RIGHT-SHADED WHITE RIGHTWARDS ARROW
0x027AA: r"\ding{234}", # LEFT-SHADED WHITE RIGHTWARDS ARROW
0x027AB: r"\ding{235}", # BACK-TILTED SHADOWED WHITE RIGHTWARDS ARROW
0x027AC: r"\ding{236}", # FRONT-TILTED SHADOWED WHITE RIGHTWARDS ARROW
0x027AD: r"\ding{237}", # HEAVY LOWER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW
0x027AE: r"\ding{238}", # HEAVY UPPER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW
0x027AF: r"\ding{239}", # NOTCHED LOWER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW
0x027B1: r"\ding{241}", # NOTCHED UPPER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW
0x027B2: r"\ding{242}", # CIRCLED HEAVY WHITE RIGHTWARDS ARROW
0x027B3: r"\ding{243}", # WHITE-FEATHERED RIGHTWARDS ARROW
0x027B4: r"\ding{244}", # BLACK-FEATHERED SOUTH EAST ARROW
0x027B5: r"\ding{245}", # BLACK-FEATHERED RIGHTWARDS ARROW
0x027B6: r"\ding{246}", # BLACK-FEATHERED NORTH EAST ARROW
0x027B7: r"\ding{247}", # HEAVY BLACK-FEATHERED SOUTH EAST ARROW
0x027B8: r"\ding{248}", # HEAVY BLACK-FEATHERED RIGHTWARDS ARROW
0x027B9: r"\ding{249}", # HEAVY BLACK-FEATHERED NORTH EAST ARROW
0x027BA: r"\ding{250}", # TEARDROP-BARBED RIGHTWARDS ARROW
0x027BB: r"\ding{251}", # HEAVY TEARDROP-SHANKED RIGHTWARDS ARROW
0x027BC: r"\ding{252}", # WEDGE-TAILED RIGHTWARDS ARROW
0x027BD: r"\ding{253}", # HEAVY WEDGE-TAILED RIGHTWARDS ARROW
0x027BE: r"\ding{254}", # OPEN-OUTLINED RIGHTWARDS ARROW

0x02A6E: r"$\stackrel{*}{=}$", # EQUALS WITH ASTERISK
0x02A75: r"$\Equal$", # TWO CONSECUTIVE EQUALS SIGNS
0x02A7D: r"$\leqslant$", # LESS-THAN OR SLANTED EQUAL TO
0x02A7E: r"$\geqslant$", # GREATER-THAN OR SLANTED EQUAL TO
0x02A85: r"$\lessapprox$", # LESS-THAN OR APPROXIMATE
0x02A86: r"$\gtrapprox$", # GREATER-THAN OR APPROXIMATE
0x02A87: r"$\lneq$", # LESS-THAN AND SINGLE-LINE NOT EQUAL TO
0x02A88: r"$\gneq$", # GREATER-THAN AND SINGLE-LINE NOT EQUAL TO
0x02A89: r"$\lnapprox$", # LESS-THAN AND NOT APPROXIMATE
0x02A8A: r"$\gnapprox$", # GREATER-THAN AND NOT APPROXIMATE
0x02A8B: r"$\lesseqqgtr$", # LESS-THAN ABOVE DOUBLE-LINE EQUAL ABOVE GREATER-THAN
0x02A8C: r"$\gtreqqless$", # GREATER-THAN ABOVE DOUBLE-LINE EQUAL ABOVE LESS-THAN
0x02A95: r"$\eqslantless$", # SLANTED EQUAL TO OR LESS-THAN
0x02A96: r"$\eqslantgtr$", # SLANTED EQUAL TO OR GREATER-THAN
0x02A9D: r"$\Pisymbol{ppi020}{117}$", # SIMILAR OR LESS-THAN
0x02A9E: r"$\Pisymbol{ppi020}{105}$", # SIMILAR OR GREATER-THAN
0x02AA1: r"$\NestedLessLess$", # DOUBLE NESTED LESS-THAN
0x02AA2: r"$\NestedGreaterGreater$", # DOUBLE NESTED GREATER-THAN
0x02AAF: r"$\preceq$", # PRECEDES ABOVE SINGLE-LINE EQUALS SIGN
0x02AB0: r"$\succeq$", # SUCCEEDS ABOVE SINGLE-LINE EQUALS SIGN
0x02AB5: r"$\precneqq$", # PRECEDES ABOVE NOT EQUAL TO
0x02AB6: r"$\succneqq$", # SUCCEEDS ABOVE NOT EQUAL TO
0x02AB7: r"$\precapprox$", # PRECEDES ABOVE ALMOST EQUAL TO
0x02AB8: r"$\succapprox$", # SUCCEEDS ABOVE ALMOST EQUAL TO
0x02AB9: r"$\precnapprox$", # PRECEDES ABOVE NOT ALMOST EQUAL TO
0x02ABA: r"$\succnapprox$", # SUCCEEDS ABOVE NOT ALMOST EQUAL TO
0x02AC5: r"$\subseteqq$", # SUBSET OF ABOVE EQUALS SIGN
0x02AC6: r"$\supseteqq$", # SUPERSET OF ABOVE EQUALS SIGN
0x02ACB: r"$\subsetneqq$", # SUBSET OF ABOVE NOT EQUAL TO
0x02ACC: r"$\supsetneqq$", # SUPERSET OF ABOVE NOT EQUAL TO

0x0FB00: r"ff", # LATIN SMALL LIGATURE FF
0x0FB01: r"fi", # LATIN SMALL LIGATURE FI
0x0FB02: r"fl", # LATIN SMALL LIGATURE FL
0x0FB03: r"ffi", # LATIN SMALL LIGATURE FFI
0x0FB04: r"ffl", # LATIN SMALL LIGATURE FFL
0x1D6B9: r"\mathbf{\vartheta}", # MATHEMATICAL BOLD CAPITAL THETA SYMBOL
0x1D6DD: r"\mathbf{\vartheta}", # MATHEMATICAL BOLD THETA SYMBOL
0x1D6DE: r"\mathbf{\varkappa}", # MATHEMATICAL BOLD KAPPA SYMBOL
0x1D6DF: r"\mathbf{\phi}", # MATHEMATICAL BOLD PHI SYMBOL
0x1D6E0: r"\mathbf{\varrho}", # MATHEMATICAL BOLD RHO SYMBOL
0x1D6E1: r"\mathbf{\varpi}", # MATHEMATICAL BOLD PI SYMBOL
0x1D6F3: r"\mathsl{\vartheta}", # MATHEMATICAL ITALIC CAPITAL THETA SYMBOL
0x1D717: r"\mathsl{\vartheta}", # MATHEMATICAL ITALIC THETA SYMBOL
0x1D718: r"\mathsl{\varkappa}", # MATHEMATICAL ITALIC KAPPA SYMBOL
0x1D719: r"\mathsl{\phi}", # MATHEMATICAL ITALIC PHI SYMBOL
0x1D71A: r"\mathsl{\varrho}", # MATHEMATICAL ITALIC RHO SYMBOL
0x1D71B: r"\mathsl{\varpi}", # MATHEMATICAL ITALIC PI SYMBOL
0x1D72D: r"\mathbit{O}", # MATHEMATICAL BOLD ITALIC CAPITAL THETA SYMBOL
0x1D751: r"\mathbit{\vartheta}", # MATHEMATICAL BOLD ITALIC THETA SYMBOL
0x1D752: r"\mathbit{\varkappa}", # MATHEMATICAL BOLD ITALIC KAPPA SYMBOL
0x1D753: r"\mathbit{\phi}", # MATHEMATICAL BOLD ITALIC PHI SYMBOL
0x1D754: r"\mathbit{\varrho}", # MATHEMATICAL BOLD ITALIC RHO SYMBOL
0x1D755: r"\mathbit{\varpi}", # MATHEMATICAL BOLD ITALIC PI SYMBOL
0x1D767: r"\mathsfbf{\vartheta}", # MATHEMATICAL SANS-SERIF BOLD CAPITAL THETA SYMBOL
0x1D78B: r"\mathsfbf{\vartheta}", # MATHEMATICAL SANS-SERIF BOLD THETA SYMBOL
0x1D78C: r"\mathsfbf{\varkappa}", # MATHEMATICAL SANS-SERIF BOLD KAPPA SYMBOL
0x1D78D: r"\mathsfbf{\phi}", # MATHEMATICAL SANS-SERIF BOLD PHI SYMBOL
0x1D78E: r"\mathsfbf{\varrho}", # MATHEMATICAL SANS-SERIF BOLD RHO SYMBOL
0x1D78F: r"\mathsfbf{\varpi}", # MATHEMATICAL SANS-SERIF BOLD PI SYMBOL
0x1D7A1: r"\mathsfbfsl{\vartheta}", # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL THETA SYMBOL
0x1D7C5: r"\mathsfbfsl{\vartheta}", # MATHEMATICAL SANS-SERIF BOLD ITALIC THETA SYMBOL
0x1D7C6: r"\mathsfbfsl{\varkappa}", # MATHEMATICAL SANS-SERIF BOLD ITALIC KAPPA SYMBOL
0x1D7C7: r"\mathsfbfsl{\phi}", # MATHEMATICAL SANS-SERIF BOLD ITALIC PHI SYMBOL
0x1D7C8: r"\mathsfbfsl{\varrho}", # MATHEMATICAL SANS-SERIF BOLD ITALIC RHO SYMBOL
0x1D7C9: r"\mathsfbfsl{\varpi}", # MATHEMATICAL SANS-SERIF BOLD ITALIC PI SYMBOL
}
