<?xml version='1.0'?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version='1.0'>

<!--############################################################################
    Feuille de style de transformation XML DocBook -> LaTeX 
    ############################################################################ -->


<xsl:variable name="doc.section.depth">5</xsl:variable>
<xsl:variable name="toc.section.depth">5</xsl:variable>
<xsl:variable name="latex.figure.position">[htbp]</xsl:variable>
<xsl:variable name="latex.use.hyperref">0</xsl:variable>

<xsl:template name="number.xref">
<xsl:text>\ref{</xsl:text><xsl:value-of select="@id"/><xsl:text>}</xsl:text>
</xsl:template>


<xsl:variable name="latex.book.preamblestart">
<xsl:text>% -----------------------------------------  &#10;</xsl:text>
<xsl:text>% Autogenerated LaTeX file from XML DocBook  &#10;</xsl:text>
<xsl:text>% -----------------------------------------  &#10;</xsl:text>
<xsl:text>\documentclass{report}&#10;</xsl:text>
<xsl:text>\usepackage[T1]{fontenc}&#10;</xsl:text>
<xsl:text>\usepackage[latin1]{inputenc}&#10;</xsl:text>
<xsl:text>\usepackage{a4wide}&#10;</xsl:text>
<xsl:text>\setcounter{secnumdepth}{5}&#10;</xsl:text>
<xsl:text>\setlength\parskip{\medskipamount} &#10;</xsl:text>
<xsl:text>\setlength\parindent{0pt}          &#10;</xsl:text>
<xsl:text>\usepackage{fancybox}&#10;</xsl:text>
<xsl:text>\usepackage{makeidx}&#10;</xsl:text>
</xsl:variable>

<xsl:variable name="latex.article.preamblestart">
<xsl:text>% -----------------------------------------  &#10;</xsl:text>
<xsl:text>% Autogenerated LaTeX file from XML DocBook  &#10;</xsl:text>
<xsl:text>% -----------------------------------------  &#10;</xsl:text>
<xsl:text>\documentclass{article}&#10;</xsl:text>
<xsl:text>\usepackage[T1]{fontenc}&#10;</xsl:text>
<xsl:text>\usepackage[latin1]{inputenc}&#10;</xsl:text>
<xsl:text>\usepackage{a4wide}&#10;</xsl:text>
<xsl:text>\setcounter{secnumdepth}{5}&#10;</xsl:text>
<xsl:text>\setlength\parskip{\medskipamount} &#10;</xsl:text>
<xsl:text>\setlength\parindent{0pt}          &#10;</xsl:text>
<xsl:text>\usepackage{fancybox}&#10;</xsl:text>
<xsl:text>\usepackage{makeidx}&#10;</xsl:text>
</xsl:variable>


<xsl:template match="ulink">
  <xsl:text>\href{</xsl:text>
  <xsl:value-of select="@url"/>
  <xsl:text>}{</xsl:text>
  <!-- LaTeX chars are scaped. Each / except the :// is mapped to a /\- -->
  <xsl:apply-templates mode="slash.hyphen"/>
  <xsl:text>}</xsl:text>
</xsl:template>


<!-- Les appels a \hypertarget sont supprimes car ils ajoutent un espace
     vertical, et sont sans utilite... -->

<xsl:template name="element.and.label">
  <xsl:call-template name="label.id">
    <xsl:with-param name="string">
      <xsl:call-template name="latex.mapping">
        <xsl:with-param name="keyword" select="local-name(.)"/>
      </xsl:call-template>
      <xsl:call-template name="normalize-scape">
        <xsl:with-param name="string" select="title"/>
      </xsl:call-template>
      <xsl:text>}</xsl:text> 
    </xsl:with-param>
  </xsl:call-template>
</xsl:template>


<xsl:template name="label.id">
  <xsl:param name="object" select="."/>
  <xsl:param name="string" select="''"/>
  <xsl:variable name="id">
    <xsl:choose>
      <xsl:when test="$object/@id">
 	     <xsl:value-of select="$object/@id"/>
      </xsl:when>
      <xsl:otherwise>
 	     <xsl:value-of select="''"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:variable>

  <xsl:choose>
  <xsl:when test="$id!=''">
    <!--
    <xsl:text>\hypertarget{</xsl:text>
    <xsl:value-of select="normalize-space($id)"/>
    <xsl:text>}{</xsl:text>
 	  <xsl:value-of select="$string"/>
    <xsl:text>}</xsl:text>
    -->
 	  <xsl:value-of select="$string"/>
    <xsl:text>\label{</xsl:text><xsl:value-of select="normalize-space($id)"/>
    <xsl:text>}&#10;</xsl:text>
  </xsl:when>
  <xsl:otherwise>
 	  <xsl:value-of select="$string"/>
  </xsl:otherwise>
  </xsl:choose>
</xsl:template>

<xsl:template match="chapter">
  <xsl:text>&#10;</xsl:text>
  <xsl:text>% ------------------------------------ &#10;</xsl:text>
  <xsl:text>% Chapter </xsl:text>
  <xsl:value-of select="normalize-space(title)"/>
  <xsl:text>  &#10;</xsl:text>
  <xsl:text>% ------------------------------------ &#10;</xsl:text>
  <xsl:call-template name="element.and.label"/>
  <xsl:text>\thispagestyle{fancy}&#10;</xsl:text>
  <xsl:apply-templates/>
</xsl:template>

<xsl:template name="docinfo">
  <xsl:param name="info" select="."/>
  <xsl:if test="$info/releaseinfo">
    <xsl:text>\renewcommand{\DBKreleaseinfo}{</xsl:text>
    <xsl:value-of select="normalize-space($info/releaseinfo)"/>
    <xsltext>}&#10;</xsltext>
  </xsl:if>
  <xsl:if test="$info/pubsnumber">
    <xsl:text>\renewcommand{\DBKreference}{</xsl:text>
    <xsl:value-of select="normalize-space($info/pubsnumber)"/>
    <xsl:text>}&#10;</xsl:text>
  </xsl:if>
  <xsl:if test="$info/address">
    <xsl:text>\renewcommand{\DBKsite}{</xsl:text>
    <xsl:value-of select="normalize-space($info/address)"/>
    <xsl:text>}&#10;</xsl:text>
  </xsl:if>
  <xsl:if test="$info/edition">
    <xsl:text>\renewcommand{\DBKedition}{</xsl:text>
    <xsl:call-template name="normalize-scape">
      <xsl:with-param name="string" select="$info/edition"/>
    </xsl:call-template>
    <xsl:text>}&#10;</xsl:text>
  </xsl:if>
  <xsl:if test="$info/subtitle">
    <xsl:text>\renewcommand{\DBKsubtitle}{</xsl:text>
    <xsl:call-template name="normalize-scape">
      <xsl:with-param name="string" select="$info/subtitle"/>
    </xsl:call-template>
    <xsl:text>}&#10;</xsl:text>
  </xsl:if>
  <!-- Override the date definition if specified -->
  <xsl:if test="$info/date">
    <xsl:text>\renewcommand{\DBKdate}{</xsl:text>
    <xsl:value-of select="normalize-space($info/date)"/>
    <xsl:text>}&#10;</xsl:text>
  </xsl:if>
</xsl:template>

<xsl:template match="book">
<xsl:value-of select="$latex.book.preamblestart"/>
<xsl:if test="$latex.hyperparam">
  <xsl:text>\def\hyperparam{</xsl:text>
  <xsl:value-of select="$latex.hyperparam"/>
  <xsl:text>}&#10;</xsl:text>
</xsl:if>
<xsl:text>
\usepackage[hyperlink</xsl:text>
<xsl:if test="@lang">
  <xsl:text>,</xsl:text>
  <xsl:value-of select="@lang"/>
</xsl:if>
<xsl:text>]{</xsl:text>
<xsl:value-of select="$latex.style"/>
<xsl:text>}
</xsl:text>

<xsl:call-template name="docinfo">
  <xsl:with-param name="info" select="bookinfo"/>
</xsl:call-template>

<!-- Override the infos if specified here -->
<xsl:if test="subtitle">
  <xsl:text>\renewcommand{\DBKsubtitle}{</xsl:text>
  <xsl:call-template name="normalize-scape">
    <xsl:with-param name="string" select="subtitle"/>
  </xsl:call-template>
  <xsl:text>}&#10;</xsl:text>
</xsl:if>

<xsl:text>\title{</xsl:text>
  <xsl:call-template name="normalize-scape">
    <xsl:with-param name="string">
      <xsl:choose>
      <xsl:when test="./title">
        <xsl:value-of select="./title"/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="./bookinfo/title"/>
      </xsl:otherwise>
      </xsl:choose>
    </xsl:with-param>
  </xsl:call-template>
<xsl:text>}&#10;</xsl:text>

<!-- Get the Author -->
<xsl:variable name="author">
  <xsl:choose>
    <xsl:when test="bookinfo/authorgroup/author">
      <xsl:apply-templates select="bookinfo/authorgroup"/>
    </xsl:when>
    <xsl:otherwise>
      <xsl:apply-templates select="bookinfo/author"/>
    </xsl:otherwise>
  </xsl:choose>
</xsl:variable>

<xsl:text>\author{</xsl:text>
<xsl:value-of select="$author"/>
<xsl:text>}&#10;</xsl:text>

<!-- Set the indexation table -->
% ------------------
% Table d'Indexation
% ------------------
\renewcommand{\DBKindexation}{
\begin{DBKindtable}
\DBKinditem{\writtenby}{<xsl:value-of select="$author"/>}
<xsl:apply-templates select=".//othercredit"/>
\end{DBKindtable}
}

<xsl:value-of select="$latex.book.afterauthor"/>
<xsl:text>&#10;\setcounter{tocdepth}{</xsl:text>
<xsl:value-of select="$toc.section.depth"/>
<xsl:text>}&#10;</xsl:text>
<xsl:text>&#10;\setcounter{secnumdepth}{</xsl:text>
<xsl:value-of select="$doc.section.depth"/>
<xsl:text>}&#10;</xsl:text>

<!-- Apply the revision history here -->
<xsl:if test="bookinfo/revhistory">
  <xsl:apply-templates select="bookinfo/revhistory"/>
</xsl:if>

<xsl:value-of select="$latex.book.begindocument"/>
<xsl:text>\long\def\hyper@section@backref#1#2#3{%&#10;</xsl:text>
<xsl:text>\typeout{BACK REF #1 / #2 / #3}%&#10;</xsl:text>
<xsl:text>\hyperlink{#3}{#2}}&#10;</xsl:text>
<xsl:text>&#10;</xsl:text>
<xsl:text>\maketitle&#10;</xsl:text>
<xsl:text>\tableofcontents&#10;</xsl:text>
<xsl:call-template name="label.id"/>

<!-- Apply templates -->
<xsl:apply-templates/>
<xsl:if test="*//indexterm">
 <xsl:text>\printindex&#10;</xsl:text>
</xsl:if>
<xsl:value-of select="$latex.book.end"/>
</xsl:template>

<xsl:template match="book/bookinfo">
</xsl:template>

<xsl:template match="othercredit">
<xsl:text>\DBKinditem{</xsl:text>
<xsl:value-of select="contrib"/>
<xsl:text>}{</xsl:text>
<xsl:value-of select="firstname"/>
<xsl:text> </xsl:text>
<xsl:value-of select="surname"/>
<xsl:text>}&#10;</xsl:text>
</xsl:template>


<!-- ************
     For articles
     ************ -->

<xsl:template match="article">
<xsl:value-of select="$latex.article.preamblestart"/>
<xsl:if test="$latex.hyperparam">
  <xsl:text>\def\hyperparam{</xsl:text>
  <xsl:value-of select="$latex.hyperparam"/>
  <xsl:text>}&#10;</xsl:text>
</xsl:if>
<xsl:text>
\usepackage[article,hyperlink</xsl:text>
<xsl:if test="@lang">
  <xsl:text>,</xsl:text>
  <xsl:value-of select="@lang"/>
</xsl:if>
<xsl:text>]{</xsl:text>
<xsl:value-of select="$latex.style"/>
<xsl:text>}&#10;</xsl:text>

<xsl:call-template name="docinfo">
  <xsl:with-param name="info" select="articleinfo"/>
</xsl:call-template>

<!-- Override the infos if specified here -->
<xsl:if test="subtitle">
  <xsl:text>\renewcommand{\DBKsubtitle}{</xsl:text>
  <xsl:call-template name="normalize-scape">
    <xsl:with-param name="string" select="subtitle"/>
  </xsl:call-template>
  <xsl:text>}&#10;</xsl:text>
</xsl:if>

<!-- Output title information -->
<xsl:text>\title{</xsl:text>
  <xsl:call-template name="normalize-scape">
    <xsl:with-param name="string">
      <xsl:choose>
      <xsl:when test="./title">
        <xsl:value-of select="./title"/>
      </xsl:when>
      <xsl:when test="./articleinfo/title">
        <xsl:value-of select="./articleinfo/title"/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="./artheader/title"/>
      </xsl:otherwise>
      </xsl:choose>
    </xsl:with-param>
  </xsl:call-template>
<xsl:text>}&#10;</xsl:text>

<!-- Get the Author -->
<xsl:variable name="author">
  <xsl:choose>
    <xsl:when test="articleinfo/authorgroup/author">
      <xsl:apply-templates select="articleinfo/authorgroup"/>
    </xsl:when>
    <xsl:when test="artheader/author">
      <xsl:apply-templates select="artheader/author"/>
    </xsl:when>
    <xsl:otherwise>
      <xsl:apply-templates select="articleinfo/author"/>
    </xsl:otherwise>
  </xsl:choose>
</xsl:variable>

<xsl:text>\author{</xsl:text>
<xsl:value-of select="$author"/>
<xsl:text>}&#10;</xsl:text>

<!-- Set the indexation table -->
% ------------------
% Table d'Indexation
% ------------------
\renewcommand{\DBKindexation}{
\begin{DBKindtable}
\DBKinditem{\writtenby}{<xsl:value-of select="$author"/>}
<xsl:apply-templates select=".//othercredit"/>
\end{DBKindtable}
}

<xsl:value-of select="$latex.book.afterauthor"/>
<xsl:text>&#10;\setcounter{tocdepth}{</xsl:text>
<xsl:value-of select="$toc.section.depth"/>
<xsl:text>}&#10;</xsl:text>
<xsl:text>&#10;\setcounter{secnumdepth}{</xsl:text>
<xsl:value-of select="$doc.section.depth"/>
<xsl:text>}&#10;</xsl:text>

<!-- Apply the revision history here -->
<xsl:if test="articleinfo/revhistory">
  <xsl:apply-templates select="articleinfo/revhistory"/>
</xsl:if>

<xsl:value-of select="$latex.book.begindocument"/>
<xsl:text>\long\def\hyper@section@backref#1#2#3{%&#10;</xsl:text>
<xsl:text>\typeout{BACK REF #1 / #2 / #3}%&#10;</xsl:text>
<xsl:text>\hyperlink{#3}{#2}}&#10;</xsl:text>
<xsl:text>&#10;</xsl:text>
<xsl:text>\maketitle&#10;</xsl:text>
<xsl:text>\tableofcontents&#10;</xsl:text>
<xsl:call-template name="label.id"/>

<!-- Apply templates -->
<xsl:apply-templates/>
<xsl:value-of select="$latex.book.end"/>
</xsl:template>

<xsl:template match="book/articleinfo">
</xsl:template>


<xsl:template name="generate.latex.common.preamble"/>


</xsl:stylesheet>
