#! /usr/bin/env python3
import sys
import os

package_base = os.path.join(os.path.dirname(sys.argv[0]), "..")
sys.path.insert(0, os.path.realpath(os.path.join(package_base, "lib")))

from dbtexmf.dblatex import dblatex
dblatex.main(base=package_base)
