#! /usr/bin/env python
import sys
import os

package_base = r"/usr/share/dblatex"
sys.path.append(os.path.realpath(os.path.join(package_base, "lib")))

# Register the Debian error analyser
from dbtexmf.core import error
from contrib.debian.errorhandler import DebianHandler
error.set_errhandler(DebianHandler())

from dbtexmf.dblatex import dblatex
dblatex.main(base=package_base)
